/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edwin.manufacture.cop;

import com.edwin.clickfunction.OpenFileDialg;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.edwin.manufacture.cop//BatchImportReturnOfGoodsByXlsSheet//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "BatchImportReturnOfGoodsByXlsSheetTopComponent",
        iconBase = "ICONS/canvas.gif",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "销售", id = "com.edwin.manufacture.cop.BatchImportReturnOfGoodsByXlsSheetTopComponent")
@ActionReference(path = "Menu/销售/退货" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_BatchImportReturnOfGoodsByXlsSheetAction",
        preferredID = "BatchImportReturnOfGoodsByXlsSheetTopComponent"
)
@Messages({
    "CTL_BatchImportReturnOfGoodsByXlsSheetAction=退货批量导入",
    "CTL_BatchImportReturnOfGoodsByXlsSheetTopComponent=退货批量导入",
    "HINT_BatchImportReturnOfGoodsByXlsSheetTopComponent=This is a BatchImportReturnOfGoodsByXlsSheet window"
})
public final class BatchImportReturnOfGoodsByXlsSheetTopComponent extends TopComponent {

    public BatchImportReturnOfGoodsByXlsSheetTopComponent() {
        initComponents();
        setName(Bundle.CTL_BatchImportReturnOfGoodsByXlsSheetTopComponent());
        setToolTipText(Bundle.HINT_BatchImportReturnOfGoodsByXlsSheetTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tx_absolutFilePath = new javax.swing.JTextField();
        btn_OpenFindFileDialog = new javax.swing.JButton();
        btn_CheckAndImportFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ShowXlsDetail = new com.edwin.myswingx.MyJXTable();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(BatchImportReturnOfGoodsByXlsSheetTopComponent.class, "BatchImportReturnOfGoodsByXlsSheetTopComponent.jLabel1.text")); // NOI18N

        tx_absolutFilePath.setText(org.openide.util.NbBundle.getMessage(BatchImportReturnOfGoodsByXlsSheetTopComponent.class, "BatchImportReturnOfGoodsByXlsSheetTopComponent.tx_absolutFilePath.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btn_OpenFindFileDialog, org.openide.util.NbBundle.getMessage(BatchImportReturnOfGoodsByXlsSheetTopComponent.class, "BatchImportReturnOfGoodsByXlsSheetTopComponent.btn_OpenFindFileDialog.text")); // NOI18N
        btn_OpenFindFileDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OpenFindFileDialogActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btn_CheckAndImportFile, org.openide.util.NbBundle.getMessage(BatchImportReturnOfGoodsByXlsSheetTopComponent.class, "BatchImportReturnOfGoodsByXlsSheetTopComponent.btn_CheckAndImportFile.text")); // NOI18N
        btn_CheckAndImportFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckAndImportFileActionPerformed(evt);
            }
        });

        tb_ShowXlsDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_ShowXlsDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tx_absolutFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_OpenFindFileDialog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CheckAndImportFile))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tx_absolutFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_OpenFindFileDialog)
                    .addComponent(btn_CheckAndImportFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_OpenFindFileDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OpenFindFileDialogActionPerformed
        OpenFileDialg openFileDialog = new OpenFileDialg();
        String filePath = "";
        filePath = openFileDialog.getAbsolutFilePath();
        tx_absolutFilePath.setText(filePath);   
    }//GEN-LAST:event_btn_OpenFindFileDialogActionPerformed

    private void btn_CheckAndImportFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckAndImportFileActionPerformed
        
        
    }//GEN-LAST:event_btn_CheckAndImportFileActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CheckAndImportFile;
    private javax.swing.JButton btn_OpenFindFileDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.edwin.myswingx.MyJXTable tb_ShowXlsDetail;
    private javax.swing.JTextField tx_absolutFilePath;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
