/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edwin.COP;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.edwin.COP//ChangeOrderPrice//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "ChangeOrderPriceTopComponent",
        iconBase = "com/edwin/COP/medal_gold_3.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "com.edwin.COP.ChangeOrderPriceTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ChangeOrderPriceAction",
        preferredID = "ChangeOrderPriceTopComponent")
@Messages({
    "CTL_ChangeOrderPriceAction=ChangeOrderPrice",
    "CTL_ChangeOrderPriceTopComponent=ChangeOrderPrice Window",
    "HINT_ChangeOrderPriceTopComponent=This is a ChangeOrderPrice window"
})
public final class ChangeOrderPriceTopComponent extends TopComponent {

    public ChangeOrderPriceTopComponent() {
        initComponents();
        setName(Bundle.CTL_ChangeOrderPriceTopComponent());
        setToolTipText(Bundle.HINT_ChangeOrderPriceTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
