package com.edwin.COPTABLE;
// Generated Sep 12, 2013 8:08:54 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Coptc generated by hbm2java
 */
public class Coptc  implements java.io.Serializable {


     private CoptcId id;
     private String company;
     private String creator;
     private String usrGroup;
     private String createDate;
     private String modifier;
     private String modiDate;
     private Short flag;
     private String tc003;
     private String tc004;
     private String tc005;
     private String tc006;
     private String tc007;
     private String tc008;
     private BigDecimal tc009;
     private String tc010;
     private String tc011;
     private String tc012;
     private String tc013;
     private String tc014;
     private String tc015;
     private Character tc016;
     private String tc017;
     private String tc018;
     private Character tc019;
     private String tc020;
     private String tc021;
     private String tc022;
     private String tc023;
     private String tc024;
     private String tc025;
     private BigDecimal tc026;
     private Character tc027;
     private Boolean tc028;
     private BigDecimal tc029;
     private BigDecimal tc030;
     private BigDecimal tc031;
     private String tc032;
     private String tc033;
     private String tc034;
     private String tc035;
     private String tc036;
     private String tc037;
     private String tc038;
     private String tc039;
     private String tc040;
     private BigDecimal tc041;
     private String tc042;
     private BigDecimal tc043;
     private BigDecimal tc044;
     private BigDecimal tc045;
     private BigDecimal tc046;
     private String tc047;
     private Character tc048;
     private String tc049;
     private Character tc050;
     private String tc051;
     private String tc052;
     private String tc053;
     private String tc054;
     private String tc055;
     private String tc056;
     private String tc057;
     private Boolean tc058;
     private Character tc059;
     private String tc060;
     private String tc061;
     private BigDecimal tc062;
     private BigDecimal tc063;
     private BigDecimal tc064;
     private String tc065;
     private String tc066;
     private Character tc067;
     private BigDecimal tc068;
     private BigDecimal tc069;
     private Character tc070;
     private Character tc071;
     private Character tc072;
     private String tc073;
     private String tc074;
     private String tc075;
     private String tc076;
     private String tci01;
     private String tci02;
     private BigDecimal tci03;
     private BigDecimal tci04;
     private String tc077;
     private String udf01;
     private String udf02;
     private String udf03;
     private String udf04;
     private String udf05;
     private String udf06;
     private BigDecimal udf51;
     private BigDecimal udf52;
     private BigDecimal udf53;
     private BigDecimal udf54;
     private BigDecimal udf55;
     private BigDecimal udf56;
     private String udf07;
     private String udf08;
     private String udf09;
     private String udf10;
     private String udf11;
     private String udf12;
     private BigDecimal udf57;
     private BigDecimal udf58;
     private BigDecimal udf59;
     private BigDecimal udf60;
     private BigDecimal udf61;
     private BigDecimal udf62;

    public Coptc() {
    }

	
    public Coptc(CoptcId id) {
        this.id = id;
    }
    public Coptc(CoptcId id, String company, String creator, String usrGroup, String createDate, String modifier, String modiDate, Short flag, String tc003, String tc004, String tc005, String tc006, String tc007, String tc008, BigDecimal tc009, String tc010, String tc011, String tc012, String tc013, String tc014, String tc015, Character tc016, String tc017, String tc018, Character tc019, String tc020, String tc021, String tc022, String tc023, String tc024, String tc025, BigDecimal tc026, Character tc027, Boolean tc028, BigDecimal tc029, BigDecimal tc030, BigDecimal tc031, String tc032, String tc033, String tc034, String tc035, String tc036, String tc037, String tc038, String tc039, String tc040, BigDecimal tc041, String tc042, BigDecimal tc043, BigDecimal tc044, BigDecimal tc045, BigDecimal tc046, String tc047, Character tc048, String tc049, Character tc050, String tc051, String tc052, String tc053, String tc054, String tc055, String tc056, String tc057, Boolean tc058, Character tc059, String tc060, String tc061, BigDecimal tc062, BigDecimal tc063, BigDecimal tc064, String tc065, String tc066, Character tc067, BigDecimal tc068, BigDecimal tc069, Character tc070, Character tc071, Character tc072, String tc073, String tc074, String tc075, String tc076, String tci01, String tci02, BigDecimal tci03, BigDecimal tci04, String tc077, String udf01, String udf02, String udf03, String udf04, String udf05, String udf06, BigDecimal udf51, BigDecimal udf52, BigDecimal udf53, BigDecimal udf54, BigDecimal udf55, BigDecimal udf56, String udf07, String udf08, String udf09, String udf10, String udf11, String udf12, BigDecimal udf57, BigDecimal udf58, BigDecimal udf59, BigDecimal udf60, BigDecimal udf61, BigDecimal udf62) {
       this.id = id;
       this.company = company;
       this.creator = creator;
       this.usrGroup = usrGroup;
       this.createDate = createDate;
       this.modifier = modifier;
       this.modiDate = modiDate;
       this.flag = flag;
       this.tc003 = tc003;
       this.tc004 = tc004;
       this.tc005 = tc005;
       this.tc006 = tc006;
       this.tc007 = tc007;
       this.tc008 = tc008;
       this.tc009 = tc009;
       this.tc010 = tc010;
       this.tc011 = tc011;
       this.tc012 = tc012;
       this.tc013 = tc013;
       this.tc014 = tc014;
       this.tc015 = tc015;
       this.tc016 = tc016;
       this.tc017 = tc017;
       this.tc018 = tc018;
       this.tc019 = tc019;
       this.tc020 = tc020;
       this.tc021 = tc021;
       this.tc022 = tc022;
       this.tc023 = tc023;
       this.tc024 = tc024;
       this.tc025 = tc025;
       this.tc026 = tc026;
       this.tc027 = tc027;
       this.tc028 = tc028;
       this.tc029 = tc029;
       this.tc030 = tc030;
       this.tc031 = tc031;
       this.tc032 = tc032;
       this.tc033 = tc033;
       this.tc034 = tc034;
       this.tc035 = tc035;
       this.tc036 = tc036;
       this.tc037 = tc037;
       this.tc038 = tc038;
       this.tc039 = tc039;
       this.tc040 = tc040;
       this.tc041 = tc041;
       this.tc042 = tc042;
       this.tc043 = tc043;
       this.tc044 = tc044;
       this.tc045 = tc045;
       this.tc046 = tc046;
       this.tc047 = tc047;
       this.tc048 = tc048;
       this.tc049 = tc049;
       this.tc050 = tc050;
       this.tc051 = tc051;
       this.tc052 = tc052;
       this.tc053 = tc053;
       this.tc054 = tc054;
       this.tc055 = tc055;
       this.tc056 = tc056;
       this.tc057 = tc057;
       this.tc058 = tc058;
       this.tc059 = tc059;
       this.tc060 = tc060;
       this.tc061 = tc061;
       this.tc062 = tc062;
       this.tc063 = tc063;
       this.tc064 = tc064;
       this.tc065 = tc065;
       this.tc066 = tc066;
       this.tc067 = tc067;
       this.tc068 = tc068;
       this.tc069 = tc069;
       this.tc070 = tc070;
       this.tc071 = tc071;
       this.tc072 = tc072;
       this.tc073 = tc073;
       this.tc074 = tc074;
       this.tc075 = tc075;
       this.tc076 = tc076;
       this.tci01 = tci01;
       this.tci02 = tci02;
       this.tci03 = tci03;
       this.tci04 = tci04;
       this.tc077 = tc077;
       this.udf01 = udf01;
       this.udf02 = udf02;
       this.udf03 = udf03;
       this.udf04 = udf04;
       this.udf05 = udf05;
       this.udf06 = udf06;
       this.udf51 = udf51;
       this.udf52 = udf52;
       this.udf53 = udf53;
       this.udf54 = udf54;
       this.udf55 = udf55;
       this.udf56 = udf56;
       this.udf07 = udf07;
       this.udf08 = udf08;
       this.udf09 = udf09;
       this.udf10 = udf10;
       this.udf11 = udf11;
       this.udf12 = udf12;
       this.udf57 = udf57;
       this.udf58 = udf58;
       this.udf59 = udf59;
       this.udf60 = udf60;
       this.udf61 = udf61;
       this.udf62 = udf62;
    }
   
    public CoptcId getId() {
        return this.id;
    }
    
    public void setId(CoptcId id) {
        this.id = id;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public String getUsrGroup() {
        return this.usrGroup;
    }
    
    public void setUsrGroup(String usrGroup) {
        this.usrGroup = usrGroup;
    }
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public String getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(String modiDate) {
        this.modiDate = modiDate;
    }
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }
    public String getTc003() {
        return this.tc003;
    }
    
    public void setTc003(String tc003) {
        this.tc003 = tc003;
    }
    public String getTc004() {
        return this.tc004;
    }
    
    public void setTc004(String tc004) {
        this.tc004 = tc004;
    }
    public String getTc005() {
        return this.tc005;
    }
    
    public void setTc005(String tc005) {
        this.tc005 = tc005;
    }
    public String getTc006() {
        return this.tc006;
    }
    
    public void setTc006(String tc006) {
        this.tc006 = tc006;
    }
    public String getTc007() {
        return this.tc007;
    }
    
    public void setTc007(String tc007) {
        this.tc007 = tc007;
    }
    public String getTc008() {
        return this.tc008;
    }
    
    public void setTc008(String tc008) {
        this.tc008 = tc008;
    }
    public BigDecimal getTc009() {
        return this.tc009;
    }
    
    public void setTc009(BigDecimal tc009) {
        this.tc009 = tc009;
    }
    public String getTc010() {
        return this.tc010;
    }
    
    public void setTc010(String tc010) {
        this.tc010 = tc010;
    }
    public String getTc011() {
        return this.tc011;
    }
    
    public void setTc011(String tc011) {
        this.tc011 = tc011;
    }
    public String getTc012() {
        return this.tc012;
    }
    
    public void setTc012(String tc012) {
        this.tc012 = tc012;
    }
    public String getTc013() {
        return this.tc013;
    }
    
    public void setTc013(String tc013) {
        this.tc013 = tc013;
    }
    public String getTc014() {
        return this.tc014;
    }
    
    public void setTc014(String tc014) {
        this.tc014 = tc014;
    }
    public String getTc015() {
        return this.tc015;
    }
    
    public void setTc015(String tc015) {
        this.tc015 = tc015;
    }
    public Character getTc016() {
        return this.tc016;
    }
    
    public void setTc016(Character tc016) {
        this.tc016 = tc016;
    }
    public String getTc017() {
        return this.tc017;
    }
    
    public void setTc017(String tc017) {
        this.tc017 = tc017;
    }
    public String getTc018() {
        return this.tc018;
    }
    
    public void setTc018(String tc018) {
        this.tc018 = tc018;
    }
    public Character getTc019() {
        return this.tc019;
    }
    
    public void setTc019(Character tc019) {
        this.tc019 = tc019;
    }
    public String getTc020() {
        return this.tc020;
    }
    
    public void setTc020(String tc020) {
        this.tc020 = tc020;
    }
    public String getTc021() {
        return this.tc021;
    }
    
    public void setTc021(String tc021) {
        this.tc021 = tc021;
    }
    public String getTc022() {
        return this.tc022;
    }
    
    public void setTc022(String tc022) {
        this.tc022 = tc022;
    }
    public String getTc023() {
        return this.tc023;
    }
    
    public void setTc023(String tc023) {
        this.tc023 = tc023;
    }
    public String getTc024() {
        return this.tc024;
    }
    
    public void setTc024(String tc024) {
        this.tc024 = tc024;
    }
    public String getTc025() {
        return this.tc025;
    }
    
    public void setTc025(String tc025) {
        this.tc025 = tc025;
    }
    public BigDecimal getTc026() {
        return this.tc026;
    }
    
    public void setTc026(BigDecimal tc026) {
        this.tc026 = tc026;
    }
    public Character getTc027() {
        return this.tc027;
    }
    
    public void setTc027(Character tc027) {
        this.tc027 = tc027;
    }
    public Boolean getTc028() {
        return this.tc028;
    }
    
    public void setTc028(Boolean tc028) {
        this.tc028 = tc028;
    }
    public BigDecimal getTc029() {
        return this.tc029;
    }
    
    public void setTc029(BigDecimal tc029) {
        this.tc029 = tc029;
    }
    public BigDecimal getTc030() {
        return this.tc030;
    }
    
    public void setTc030(BigDecimal tc030) {
        this.tc030 = tc030;
    }
    public BigDecimal getTc031() {
        return this.tc031;
    }
    
    public void setTc031(BigDecimal tc031) {
        this.tc031 = tc031;
    }
    public String getTc032() {
        return this.tc032;
    }
    
    public void setTc032(String tc032) {
        this.tc032 = tc032;
    }
    public String getTc033() {
        return this.tc033;
    }
    
    public void setTc033(String tc033) {
        this.tc033 = tc033;
    }
    public String getTc034() {
        return this.tc034;
    }
    
    public void setTc034(String tc034) {
        this.tc034 = tc034;
    }
    public String getTc035() {
        return this.tc035;
    }
    
    public void setTc035(String tc035) {
        this.tc035 = tc035;
    }
    public String getTc036() {
        return this.tc036;
    }
    
    public void setTc036(String tc036) {
        this.tc036 = tc036;
    }
    public String getTc037() {
        return this.tc037;
    }
    
    public void setTc037(String tc037) {
        this.tc037 = tc037;
    }
    public String getTc038() {
        return this.tc038;
    }
    
    public void setTc038(String tc038) {
        this.tc038 = tc038;
    }
    public String getTc039() {
        return this.tc039;
    }
    
    public void setTc039(String tc039) {
        this.tc039 = tc039;
    }
    public String getTc040() {
        return this.tc040;
    }
    
    public void setTc040(String tc040) {
        this.tc040 = tc040;
    }
    public BigDecimal getTc041() {
        return this.tc041;
    }
    
    public void setTc041(BigDecimal tc041) {
        this.tc041 = tc041;
    }
    public String getTc042() {
        return this.tc042;
    }
    
    public void setTc042(String tc042) {
        this.tc042 = tc042;
    }
    public BigDecimal getTc043() {
        return this.tc043;
    }
    
    public void setTc043(BigDecimal tc043) {
        this.tc043 = tc043;
    }
    public BigDecimal getTc044() {
        return this.tc044;
    }
    
    public void setTc044(BigDecimal tc044) {
        this.tc044 = tc044;
    }
    public BigDecimal getTc045() {
        return this.tc045;
    }
    
    public void setTc045(BigDecimal tc045) {
        this.tc045 = tc045;
    }
    public BigDecimal getTc046() {
        return this.tc046;
    }
    
    public void setTc046(BigDecimal tc046) {
        this.tc046 = tc046;
    }
    public String getTc047() {
        return this.tc047;
    }
    
    public void setTc047(String tc047) {
        this.tc047 = tc047;
    }
    public Character getTc048() {
        return this.tc048;
    }
    
    public void setTc048(Character tc048) {
        this.tc048 = tc048;
    }
    public String getTc049() {
        return this.tc049;
    }
    
    public void setTc049(String tc049) {
        this.tc049 = tc049;
    }
    public Character getTc050() {
        return this.tc050;
    }
    
    public void setTc050(Character tc050) {
        this.tc050 = tc050;
    }
    public String getTc051() {
        return this.tc051;
    }
    
    public void setTc051(String tc051) {
        this.tc051 = tc051;
    }
    public String getTc052() {
        return this.tc052;
    }
    
    public void setTc052(String tc052) {
        this.tc052 = tc052;
    }
    public String getTc053() {
        return this.tc053;
    }
    
    public void setTc053(String tc053) {
        this.tc053 = tc053;
    }
    public String getTc054() {
        return this.tc054;
    }
    
    public void setTc054(String tc054) {
        this.tc054 = tc054;
    }
    public String getTc055() {
        return this.tc055;
    }
    
    public void setTc055(String tc055) {
        this.tc055 = tc055;
    }
    public String getTc056() {
        return this.tc056;
    }
    
    public void setTc056(String tc056) {
        this.tc056 = tc056;
    }
    public String getTc057() {
        return this.tc057;
    }
    
    public void setTc057(String tc057) {
        this.tc057 = tc057;
    }
    public Boolean getTc058() {
        return this.tc058;
    }
    
    public void setTc058(Boolean tc058) {
        this.tc058 = tc058;
    }
    public Character getTc059() {
        return this.tc059;
    }
    
    public void setTc059(Character tc059) {
        this.tc059 = tc059;
    }
    public String getTc060() {
        return this.tc060;
    }
    
    public void setTc060(String tc060) {
        this.tc060 = tc060;
    }
    public String getTc061() {
        return this.tc061;
    }
    
    public void setTc061(String tc061) {
        this.tc061 = tc061;
    }
    public BigDecimal getTc062() {
        return this.tc062;
    }
    
    public void setTc062(BigDecimal tc062) {
        this.tc062 = tc062;
    }
    public BigDecimal getTc063() {
        return this.tc063;
    }
    
    public void setTc063(BigDecimal tc063) {
        this.tc063 = tc063;
    }
    public BigDecimal getTc064() {
        return this.tc064;
    }
    
    public void setTc064(BigDecimal tc064) {
        this.tc064 = tc064;
    }
    public String getTc065() {
        return this.tc065;
    }
    
    public void setTc065(String tc065) {
        this.tc065 = tc065;
    }
    public String getTc066() {
        return this.tc066;
    }
    
    public void setTc066(String tc066) {
        this.tc066 = tc066;
    }
    public Character getTc067() {
        return this.tc067;
    }
    
    public void setTc067(Character tc067) {
        this.tc067 = tc067;
    }
    public BigDecimal getTc068() {
        return this.tc068;
    }
    
    public void setTc068(BigDecimal tc068) {
        this.tc068 = tc068;
    }
    public BigDecimal getTc069() {
        return this.tc069;
    }
    
    public void setTc069(BigDecimal tc069) {
        this.tc069 = tc069;
    }
    public Character getTc070() {
        return this.tc070;
    }
    
    public void setTc070(Character tc070) {
        this.tc070 = tc070;
    }
    public Character getTc071() {
        return this.tc071;
    }
    
    public void setTc071(Character tc071) {
        this.tc071 = tc071;
    }
    public Character getTc072() {
        return this.tc072;
    }
    
    public void setTc072(Character tc072) {
        this.tc072 = tc072;
    }
    public String getTc073() {
        return this.tc073;
    }
    
    public void setTc073(String tc073) {
        this.tc073 = tc073;
    }
    public String getTc074() {
        return this.tc074;
    }
    
    public void setTc074(String tc074) {
        this.tc074 = tc074;
    }
    public String getTc075() {
        return this.tc075;
    }
    
    public void setTc075(String tc075) {
        this.tc075 = tc075;
    }
    public String getTc076() {
        return this.tc076;
    }
    
    public void setTc076(String tc076) {
        this.tc076 = tc076;
    }
    public String getTci01() {
        return this.tci01;
    }
    
    public void setTci01(String tci01) {
        this.tci01 = tci01;
    }
    public String getTci02() {
        return this.tci02;
    }
    
    public void setTci02(String tci02) {
        this.tci02 = tci02;
    }
    public BigDecimal getTci03() {
        return this.tci03;
    }
    
    public void setTci03(BigDecimal tci03) {
        this.tci03 = tci03;
    }
    public BigDecimal getTci04() {
        return this.tci04;
    }
    
    public void setTci04(BigDecimal tci04) {
        this.tci04 = tci04;
    }
    public String getTc077() {
        return this.tc077;
    }
    
    public void setTc077(String tc077) {
        this.tc077 = tc077;
    }
    public String getUdf01() {
        return this.udf01;
    }
    
    public void setUdf01(String udf01) {
        this.udf01 = udf01;
    }
    public String getUdf02() {
        return this.udf02;
    }
    
    public void setUdf02(String udf02) {
        this.udf02 = udf02;
    }
    public String getUdf03() {
        return this.udf03;
    }
    
    public void setUdf03(String udf03) {
        this.udf03 = udf03;
    }
    public String getUdf04() {
        return this.udf04;
    }
    
    public void setUdf04(String udf04) {
        this.udf04 = udf04;
    }
    public String getUdf05() {
        return this.udf05;
    }
    
    public void setUdf05(String udf05) {
        this.udf05 = udf05;
    }
    public String getUdf06() {
        return this.udf06;
    }
    
    public void setUdf06(String udf06) {
        this.udf06 = udf06;
    }
    public BigDecimal getUdf51() {
        return this.udf51;
    }
    
    public void setUdf51(BigDecimal udf51) {
        this.udf51 = udf51;
    }
    public BigDecimal getUdf52() {
        return this.udf52;
    }
    
    public void setUdf52(BigDecimal udf52) {
        this.udf52 = udf52;
    }
    public BigDecimal getUdf53() {
        return this.udf53;
    }
    
    public void setUdf53(BigDecimal udf53) {
        this.udf53 = udf53;
    }
    public BigDecimal getUdf54() {
        return this.udf54;
    }
    
    public void setUdf54(BigDecimal udf54) {
        this.udf54 = udf54;
    }
    public BigDecimal getUdf55() {
        return this.udf55;
    }
    
    public void setUdf55(BigDecimal udf55) {
        this.udf55 = udf55;
    }
    public BigDecimal getUdf56() {
        return this.udf56;
    }
    
    public void setUdf56(BigDecimal udf56) {
        this.udf56 = udf56;
    }
    public String getUdf07() {
        return this.udf07;
    }
    
    public void setUdf07(String udf07) {
        this.udf07 = udf07;
    }
    public String getUdf08() {
        return this.udf08;
    }
    
    public void setUdf08(String udf08) {
        this.udf08 = udf08;
    }
    public String getUdf09() {
        return this.udf09;
    }
    
    public void setUdf09(String udf09) {
        this.udf09 = udf09;
    }
    public String getUdf10() {
        return this.udf10;
    }
    
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }
    public String getUdf11() {
        return this.udf11;
    }
    
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }
    public String getUdf12() {
        return this.udf12;
    }
    
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }
    public BigDecimal getUdf57() {
        return this.udf57;
    }
    
    public void setUdf57(BigDecimal udf57) {
        this.udf57 = udf57;
    }
    public BigDecimal getUdf58() {
        return this.udf58;
    }
    
    public void setUdf58(BigDecimal udf58) {
        this.udf58 = udf58;
    }
    public BigDecimal getUdf59() {
        return this.udf59;
    }
    
    public void setUdf59(BigDecimal udf59) {
        this.udf59 = udf59;
    }
    public BigDecimal getUdf60() {
        return this.udf60;
    }
    
    public void setUdf60(BigDecimal udf60) {
        this.udf60 = udf60;
    }
    public BigDecimal getUdf61() {
        return this.udf61;
    }
    
    public void setUdf61(BigDecimal udf61) {
        this.udf61 = udf61;
    }
    public BigDecimal getUdf62() {
        return this.udf62;
    }
    
    public void setUdf62(BigDecimal udf62) {
        this.udf62 = udf62;
    }




}


