package com.edwin.COPTABLE;
// Generated Sep 12, 2013 8:08:54 AM by Hibernate Tools 3.6.0



/**
 * CoptdId generated by hbm2java
 */
public class CoptdId  implements java.io.Serializable {


     private String td001;
     private String td002;
     private String td003;

    public CoptdId() {
    }

    public CoptdId(String td001, String td002, String td003) {
       this.td001 = td001;
       this.td002 = td002;
       this.td003 = td003;
    }
   
    public String getTd001() {
        return this.td001;
    }
    
    public void setTd001(String td001) {
        this.td001 = td001;
    }
    public String getTd002() {
        return this.td002;
    }
    
    public void setTd002(String td002) {
        this.td002 = td002;
    }
    public String getTd003() {
        return this.td003;
    }
    
    public void setTd003(String td003) {
        this.td003 = td003;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CoptdId) ) return false;
		 CoptdId castOther = ( CoptdId ) other; 
         
		 return ( (this.getTd001()==castOther.getTd001()) || ( this.getTd001()!=null && castOther.getTd001()!=null && this.getTd001().equals(castOther.getTd001()) ) )
 && ( (this.getTd002()==castOther.getTd002()) || ( this.getTd002()!=null && castOther.getTd002()!=null && this.getTd002().equals(castOther.getTd002()) ) )
 && ( (this.getTd003()==castOther.getTd003()) || ( this.getTd003()!=null && castOther.getTd003()!=null && this.getTd003().equals(castOther.getTd003()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTd001() == null ? 0 : this.getTd001().hashCode() );
         result = 37 * result + ( getTd002() == null ? 0 : this.getTd002().hashCode() );
         result = 37 * result + ( getTd003() == null ? 0 : this.getTd003().hashCode() );
         return result;
   }   


}


