package com.edwin.CWMONTH;
// Generated Jul 11, 2013 10:12:56 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * InvmbcId generated by hbm2java
 */
public class InvmbcId  implements java.io.Serializable {


     private String mb001;
     private String mb002;
     private String mb003;
     private String mb110;
     private String mb004;
     private String mb025;
     private BigDecimal materialPrice;
     private BigDecimal laborePrice;
     private BigDecimal madePrice;
     private BigDecimal cooperationPrice;
     private String dh;
     private String orderno;
     private String udf01;
     private String udf02;
     private String udf03;
     private String udf04;
     private String udf05;
     private String udf06;
     private BigDecimal udf07;
     private BigDecimal udf08;
     private BigDecimal udf09;
     private BigDecimal udf010;
     private BigDecimal udf011;
     private BigDecimal udf012;

    public InvmbcId() {
    }

	
    public InvmbcId(String mb001) {
        this.mb001 = mb001;
    }
    public InvmbcId(String mb001, String mb002, String mb003, String mb110, String mb004, String mb025, BigDecimal materialPrice, BigDecimal laborePrice, BigDecimal madePrice, BigDecimal cooperationPrice, String dh, String orderno, String udf01, String udf02, String udf03, String udf04, String udf05, String udf06, BigDecimal udf07, BigDecimal udf08, BigDecimal udf09, BigDecimal udf010, BigDecimal udf011, BigDecimal udf012) {
       this.mb001 = mb001;
       this.mb002 = mb002;
       this.mb003 = mb003;
       this.mb110 = mb110;
       this.mb004 = mb004;
       this.mb025 = mb025;
       this.materialPrice = materialPrice;
       this.laborePrice = laborePrice;
       this.madePrice = madePrice;
       this.cooperationPrice = cooperationPrice;
       this.dh = dh;
       this.orderno = orderno;
       this.udf01 = udf01;
       this.udf02 = udf02;
       this.udf03 = udf03;
       this.udf04 = udf04;
       this.udf05 = udf05;
       this.udf06 = udf06;
       this.udf07 = udf07;
       this.udf08 = udf08;
       this.udf09 = udf09;
       this.udf010 = udf010;
       this.udf011 = udf011;
       this.udf012 = udf012;
    }
   
    public String getMb001() {
        return this.mb001;
    }
    
    public void setMb001(String mb001) {
        this.mb001 = mb001;
    }
    public String getMb002() {
        return this.mb002;
    }
    
    public void setMb002(String mb002) {
        this.mb002 = mb002;
    }
    public String getMb003() {
        return this.mb003;
    }
    
    public void setMb003(String mb003) {
        this.mb003 = mb003;
    }
    public String getMb110() {
        return this.mb110;
    }
    
    public void setMb110(String mb110) {
        this.mb110 = mb110;
    }
    public String getMb004() {
        return this.mb004;
    }
    
    public void setMb004(String mb004) {
        this.mb004 = mb004;
    }
    public String getMb025() {
        return this.mb025;
    }
    
    public void setMb025(String mb025) {
        this.mb025 = mb025;
    }
    public BigDecimal getMaterialPrice() {
        return this.materialPrice;
    }
    
    public void setMaterialPrice(BigDecimal materialPrice) {
        this.materialPrice = materialPrice;
    }
    public BigDecimal getLaborePrice() {
        return this.laborePrice;
    }
    
    public void setLaborePrice(BigDecimal laborePrice) {
        this.laborePrice = laborePrice;
    }
    public BigDecimal getMadePrice() {
        return this.madePrice;
    }
    
    public void setMadePrice(BigDecimal madePrice) {
        this.madePrice = madePrice;
    }
    public BigDecimal getCooperationPrice() {
        return this.cooperationPrice;
    }
    
    public void setCooperationPrice(BigDecimal cooperationPrice) {
        this.cooperationPrice = cooperationPrice;
    }
    public String getDh() {
        return this.dh;
    }
    
    public void setDh(String dh) {
        this.dh = dh;
    }
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }
    public String getUdf01() {
        return this.udf01;
    }
    
    public void setUdf01(String udf01) {
        this.udf01 = udf01;
    }
    public String getUdf02() {
        return this.udf02;
    }
    
    public void setUdf02(String udf02) {
        this.udf02 = udf02;
    }
    public String getUdf03() {
        return this.udf03;
    }
    
    public void setUdf03(String udf03) {
        this.udf03 = udf03;
    }
    public String getUdf04() {
        return this.udf04;
    }
    
    public void setUdf04(String udf04) {
        this.udf04 = udf04;
    }
    public String getUdf05() {
        return this.udf05;
    }
    
    public void setUdf05(String udf05) {
        this.udf05 = udf05;
    }
    public String getUdf06() {
        return this.udf06;
    }
    
    public void setUdf06(String udf06) {
        this.udf06 = udf06;
    }
    public BigDecimal getUdf07() {
        return this.udf07;
    }
    
    public void setUdf07(BigDecimal udf07) {
        this.udf07 = udf07;
    }
    public BigDecimal getUdf08() {
        return this.udf08;
    }
    
    public void setUdf08(BigDecimal udf08) {
        this.udf08 = udf08;
    }
    public BigDecimal getUdf09() {
        return this.udf09;
    }
    
    public void setUdf09(BigDecimal udf09) {
        this.udf09 = udf09;
    }
    public BigDecimal getUdf010() {
        return this.udf010;
    }
    
    public void setUdf010(BigDecimal udf010) {
        this.udf010 = udf010;
    }
    public BigDecimal getUdf011() {
        return this.udf011;
    }
    
    public void setUdf011(BigDecimal udf011) {
        this.udf011 = udf011;
    }
    public BigDecimal getUdf012() {
        return this.udf012;
    }
    
    public void setUdf012(BigDecimal udf012) {
        this.udf012 = udf012;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvmbcId) ) return false;
		 InvmbcId castOther = ( InvmbcId ) other; 
         
		 return ( (this.getMb001()==castOther.getMb001()) || ( this.getMb001()!=null && castOther.getMb001()!=null && this.getMb001().equals(castOther.getMb001()) ) )
 && ( (this.getMb002()==castOther.getMb002()) || ( this.getMb002()!=null && castOther.getMb002()!=null && this.getMb002().equals(castOther.getMb002()) ) )
 && ( (this.getMb003()==castOther.getMb003()) || ( this.getMb003()!=null && castOther.getMb003()!=null && this.getMb003().equals(castOther.getMb003()) ) )
 && ( (this.getMb110()==castOther.getMb110()) || ( this.getMb110()!=null && castOther.getMb110()!=null && this.getMb110().equals(castOther.getMb110()) ) )
 && ( (this.getMb004()==castOther.getMb004()) || ( this.getMb004()!=null && castOther.getMb004()!=null && this.getMb004().equals(castOther.getMb004()) ) )
 && ( (this.getMb025()==castOther.getMb025()) || ( this.getMb025()!=null && castOther.getMb025()!=null && this.getMb025().equals(castOther.getMb025()) ) )
 && ( (this.getMaterialPrice()==castOther.getMaterialPrice()) || ( this.getMaterialPrice()!=null && castOther.getMaterialPrice()!=null && this.getMaterialPrice().equals(castOther.getMaterialPrice()) ) )
 && ( (this.getLaborePrice()==castOther.getLaborePrice()) || ( this.getLaborePrice()!=null && castOther.getLaborePrice()!=null && this.getLaborePrice().equals(castOther.getLaborePrice()) ) )
 && ( (this.getMadePrice()==castOther.getMadePrice()) || ( this.getMadePrice()!=null && castOther.getMadePrice()!=null && this.getMadePrice().equals(castOther.getMadePrice()) ) )
 && ( (this.getCooperationPrice()==castOther.getCooperationPrice()) || ( this.getCooperationPrice()!=null && castOther.getCooperationPrice()!=null && this.getCooperationPrice().equals(castOther.getCooperationPrice()) ) )
 && ( (this.getDh()==castOther.getDh()) || ( this.getDh()!=null && castOther.getDh()!=null && this.getDh().equals(castOther.getDh()) ) )
 && ( (this.getOrderno()==castOther.getOrderno()) || ( this.getOrderno()!=null && castOther.getOrderno()!=null && this.getOrderno().equals(castOther.getOrderno()) ) )
 && ( (this.getUdf01()==castOther.getUdf01()) || ( this.getUdf01()!=null && castOther.getUdf01()!=null && this.getUdf01().equals(castOther.getUdf01()) ) )
 && ( (this.getUdf02()==castOther.getUdf02()) || ( this.getUdf02()!=null && castOther.getUdf02()!=null && this.getUdf02().equals(castOther.getUdf02()) ) )
 && ( (this.getUdf03()==castOther.getUdf03()) || ( this.getUdf03()!=null && castOther.getUdf03()!=null && this.getUdf03().equals(castOther.getUdf03()) ) )
 && ( (this.getUdf04()==castOther.getUdf04()) || ( this.getUdf04()!=null && castOther.getUdf04()!=null && this.getUdf04().equals(castOther.getUdf04()) ) )
 && ( (this.getUdf05()==castOther.getUdf05()) || ( this.getUdf05()!=null && castOther.getUdf05()!=null && this.getUdf05().equals(castOther.getUdf05()) ) )
 && ( (this.getUdf06()==castOther.getUdf06()) || ( this.getUdf06()!=null && castOther.getUdf06()!=null && this.getUdf06().equals(castOther.getUdf06()) ) )
 && ( (this.getUdf07()==castOther.getUdf07()) || ( this.getUdf07()!=null && castOther.getUdf07()!=null && this.getUdf07().equals(castOther.getUdf07()) ) )
 && ( (this.getUdf08()==castOther.getUdf08()) || ( this.getUdf08()!=null && castOther.getUdf08()!=null && this.getUdf08().equals(castOther.getUdf08()) ) )
 && ( (this.getUdf09()==castOther.getUdf09()) || ( this.getUdf09()!=null && castOther.getUdf09()!=null && this.getUdf09().equals(castOther.getUdf09()) ) )
 && ( (this.getUdf010()==castOther.getUdf010()) || ( this.getUdf010()!=null && castOther.getUdf010()!=null && this.getUdf010().equals(castOther.getUdf010()) ) )
 && ( (this.getUdf011()==castOther.getUdf011()) || ( this.getUdf011()!=null && castOther.getUdf011()!=null && this.getUdf011().equals(castOther.getUdf011()) ) )
 && ( (this.getUdf012()==castOther.getUdf012()) || ( this.getUdf012()!=null && castOther.getUdf012()!=null && this.getUdf012().equals(castOther.getUdf012()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMb001() == null ? 0 : this.getMb001().hashCode() );
         result = 37 * result + ( getMb002() == null ? 0 : this.getMb002().hashCode() );
         result = 37 * result + ( getMb003() == null ? 0 : this.getMb003().hashCode() );
         result = 37 * result + ( getMb110() == null ? 0 : this.getMb110().hashCode() );
         result = 37 * result + ( getMb004() == null ? 0 : this.getMb004().hashCode() );
         result = 37 * result + ( getMb025() == null ? 0 : this.getMb025().hashCode() );
         result = 37 * result + ( getMaterialPrice() == null ? 0 : this.getMaterialPrice().hashCode() );
         result = 37 * result + ( getLaborePrice() == null ? 0 : this.getLaborePrice().hashCode() );
         result = 37 * result + ( getMadePrice() == null ? 0 : this.getMadePrice().hashCode() );
         result = 37 * result + ( getCooperationPrice() == null ? 0 : this.getCooperationPrice().hashCode() );
         result = 37 * result + ( getDh() == null ? 0 : this.getDh().hashCode() );
         result = 37 * result + ( getOrderno() == null ? 0 : this.getOrderno().hashCode() );
         result = 37 * result + ( getUdf01() == null ? 0 : this.getUdf01().hashCode() );
         result = 37 * result + ( getUdf02() == null ? 0 : this.getUdf02().hashCode() );
         result = 37 * result + ( getUdf03() == null ? 0 : this.getUdf03().hashCode() );
         result = 37 * result + ( getUdf04() == null ? 0 : this.getUdf04().hashCode() );
         result = 37 * result + ( getUdf05() == null ? 0 : this.getUdf05().hashCode() );
         result = 37 * result + ( getUdf06() == null ? 0 : this.getUdf06().hashCode() );
         result = 37 * result + ( getUdf07() == null ? 0 : this.getUdf07().hashCode() );
         result = 37 * result + ( getUdf08() == null ? 0 : this.getUdf08().hashCode() );
         result = 37 * result + ( getUdf09() == null ? 0 : this.getUdf09().hashCode() );
         result = 37 * result + ( getUdf010() == null ? 0 : this.getUdf010().hashCode() );
         result = 37 * result + ( getUdf011() == null ? 0 : this.getUdf011().hashCode() );
         result = 37 * result + ( getUdf012() == null ? 0 : this.getUdf012().hashCode() );
         return result;
   }   


}


