package com.edwin.DepartMaterial;
// Generated Jun 23, 2013 8:44:29 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Moctd generated by hbm2java
 */
public class Moctd  implements java.io.Serializable {


     private MoctdId id;
     private String company;
     private String creator;
     private String usrGroup;
     private String createDate;
     private String modifier;
     private String modiDate;
     private Short flag;
     private Character td005;
     private BigDecimal td006;
     private String td007;
     private Character td008;
     private String td009;
     private String td010;
     private String td011;
     private String td012;
     private Character td013;
     private String td014;
     private Character td015;
     private String td016;
     private Character td017;
     private String td018;
     private Character td019;
     private Character td020;
     private String td021;
     private String td022;
     private BigDecimal td023;
     private BigDecimal td024;
     private BigDecimal td025;
     private Character tdc01;
     private String td026;
     private String udf01;
     private String udf02;
     private String udf03;
     private String udf04;
     private String udf05;
     private String udf06;
     private BigDecimal udf51;
     private BigDecimal udf52;
     private BigDecimal udf53;
     private BigDecimal udf54;
     private BigDecimal udf55;
     private BigDecimal udf56;
     private String udf07;
     private String udf08;
     private String udf09;
     private String udf10;
     private String udf11;
     private String udf12;
     private BigDecimal udf57;
     private BigDecimal udf58;
     private BigDecimal udf59;
     private BigDecimal udf60;
     private BigDecimal udf61;
     private BigDecimal udf62;

    public Moctd() {
    }

	
    public Moctd(MoctdId id) {
        this.id = id;
    }
    public Moctd(MoctdId id, String company, String creator, String usrGroup, String createDate, String modifier, String modiDate, Short flag, Character td005, BigDecimal td006, String td007, Character td008, String td009, String td010, String td011, String td012, Character td013, String td014, Character td015, String td016, Character td017, String td018, Character td019, Character td020, String td021, String td022, BigDecimal td023, BigDecimal td024, BigDecimal td025, Character tdc01, String td026, String udf01, String udf02, String udf03, String udf04, String udf05, String udf06, BigDecimal udf51, BigDecimal udf52, BigDecimal udf53, BigDecimal udf54, BigDecimal udf55, BigDecimal udf56, String udf07, String udf08, String udf09, String udf10, String udf11, String udf12, BigDecimal udf57, BigDecimal udf58, BigDecimal udf59, BigDecimal udf60, BigDecimal udf61, BigDecimal udf62) {
       this.id = id;
       this.company = company;
       this.creator = creator;
       this.usrGroup = usrGroup;
       this.createDate = createDate;
       this.modifier = modifier;
       this.modiDate = modiDate;
       this.flag = flag;
       this.td005 = td005;
       this.td006 = td006;
       this.td007 = td007;
       this.td008 = td008;
       this.td009 = td009;
       this.td010 = td010;
       this.td011 = td011;
       this.td012 = td012;
       this.td013 = td013;
       this.td014 = td014;
       this.td015 = td015;
       this.td016 = td016;
       this.td017 = td017;
       this.td018 = td018;
       this.td019 = td019;
       this.td020 = td020;
       this.td021 = td021;
       this.td022 = td022;
       this.td023 = td023;
       this.td024 = td024;
       this.td025 = td025;
       this.tdc01 = tdc01;
       this.td026 = td026;
       this.udf01 = udf01;
       this.udf02 = udf02;
       this.udf03 = udf03;
       this.udf04 = udf04;
       this.udf05 = udf05;
       this.udf06 = udf06;
       this.udf51 = udf51;
       this.udf52 = udf52;
       this.udf53 = udf53;
       this.udf54 = udf54;
       this.udf55 = udf55;
       this.udf56 = udf56;
       this.udf07 = udf07;
       this.udf08 = udf08;
       this.udf09 = udf09;
       this.udf10 = udf10;
       this.udf11 = udf11;
       this.udf12 = udf12;
       this.udf57 = udf57;
       this.udf58 = udf58;
       this.udf59 = udf59;
       this.udf60 = udf60;
       this.udf61 = udf61;
       this.udf62 = udf62;
    }
   
    public MoctdId getId() {
        return this.id;
    }
    
    public void setId(MoctdId id) {
        this.id = id;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public String getUsrGroup() {
        return this.usrGroup;
    }
    
    public void setUsrGroup(String usrGroup) {
        this.usrGroup = usrGroup;
    }
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public String getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(String modiDate) {
        this.modiDate = modiDate;
    }
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }
    public Character getTd005() {
        return this.td005;
    }
    
    public void setTd005(Character td005) {
        this.td005 = td005;
    }
    public BigDecimal getTd006() {
        return this.td006;
    }
    
    public void setTd006(BigDecimal td006) {
        this.td006 = td006;
    }
    public String getTd007() {
        return this.td007;
    }
    
    public void setTd007(String td007) {
        this.td007 = td007;
    }
    public Character getTd008() {
        return this.td008;
    }
    
    public void setTd008(Character td008) {
        this.td008 = td008;
    }
    public String getTd009() {
        return this.td009;
    }
    
    public void setTd009(String td009) {
        this.td009 = td009;
    }
    public String getTd010() {
        return this.td010;
    }
    
    public void setTd010(String td010) {
        this.td010 = td010;
    }
    public String getTd011() {
        return this.td011;
    }
    
    public void setTd011(String td011) {
        this.td011 = td011;
    }
    public String getTd012() {
        return this.td012;
    }
    
    public void setTd012(String td012) {
        this.td012 = td012;
    }
    public Character getTd013() {
        return this.td013;
    }
    
    public void setTd013(Character td013) {
        this.td013 = td013;
    }
    public String getTd014() {
        return this.td014;
    }
    
    public void setTd014(String td014) {
        this.td014 = td014;
    }
    public Character getTd015() {
        return this.td015;
    }
    
    public void setTd015(Character td015) {
        this.td015 = td015;
    }
    public String getTd016() {
        return this.td016;
    }
    
    public void setTd016(String td016) {
        this.td016 = td016;
    }
    public Character getTd017() {
        return this.td017;
    }
    
    public void setTd017(Character td017) {
        this.td017 = td017;
    }
    public String getTd018() {
        return this.td018;
    }
    
    public void setTd018(String td018) {
        this.td018 = td018;
    }
    public Character getTd019() {
        return this.td019;
    }
    
    public void setTd019(Character td019) {
        this.td019 = td019;
    }
    public Character getTd020() {
        return this.td020;
    }
    
    public void setTd020(Character td020) {
        this.td020 = td020;
    }
    public String getTd021() {
        return this.td021;
    }
    
    public void setTd021(String td021) {
        this.td021 = td021;
    }
    public String getTd022() {
        return this.td022;
    }
    
    public void setTd022(String td022) {
        this.td022 = td022;
    }
    public BigDecimal getTd023() {
        return this.td023;
    }
    
    public void setTd023(BigDecimal td023) {
        this.td023 = td023;
    }
    public BigDecimal getTd024() {
        return this.td024;
    }
    
    public void setTd024(BigDecimal td024) {
        this.td024 = td024;
    }
    public BigDecimal getTd025() {
        return this.td025;
    }
    
    public void setTd025(BigDecimal td025) {
        this.td025 = td025;
    }
    public Character getTdc01() {
        return this.tdc01;
    }
    
    public void setTdc01(Character tdc01) {
        this.tdc01 = tdc01;
    }
    public String getTd026() {
        return this.td026;
    }
    
    public void setTd026(String td026) {
        this.td026 = td026;
    }
    public String getUdf01() {
        return this.udf01;
    }
    
    public void setUdf01(String udf01) {
        this.udf01 = udf01;
    }
    public String getUdf02() {
        return this.udf02;
    }
    
    public void setUdf02(String udf02) {
        this.udf02 = udf02;
    }
    public String getUdf03() {
        return this.udf03;
    }
    
    public void setUdf03(String udf03) {
        this.udf03 = udf03;
    }
    public String getUdf04() {
        return this.udf04;
    }
    
    public void setUdf04(String udf04) {
        this.udf04 = udf04;
    }
    public String getUdf05() {
        return this.udf05;
    }
    
    public void setUdf05(String udf05) {
        this.udf05 = udf05;
    }
    public String getUdf06() {
        return this.udf06;
    }
    
    public void setUdf06(String udf06) {
        this.udf06 = udf06;
    }
    public BigDecimal getUdf51() {
        return this.udf51;
    }
    
    public void setUdf51(BigDecimal udf51) {
        this.udf51 = udf51;
    }
    public BigDecimal getUdf52() {
        return this.udf52;
    }
    
    public void setUdf52(BigDecimal udf52) {
        this.udf52 = udf52;
    }
    public BigDecimal getUdf53() {
        return this.udf53;
    }
    
    public void setUdf53(BigDecimal udf53) {
        this.udf53 = udf53;
    }
    public BigDecimal getUdf54() {
        return this.udf54;
    }
    
    public void setUdf54(BigDecimal udf54) {
        this.udf54 = udf54;
    }
    public BigDecimal getUdf55() {
        return this.udf55;
    }
    
    public void setUdf55(BigDecimal udf55) {
        this.udf55 = udf55;
    }
    public BigDecimal getUdf56() {
        return this.udf56;
    }
    
    public void setUdf56(BigDecimal udf56) {
        this.udf56 = udf56;
    }
    public String getUdf07() {
        return this.udf07;
    }
    
    public void setUdf07(String udf07) {
        this.udf07 = udf07;
    }
    public String getUdf08() {
        return this.udf08;
    }
    
    public void setUdf08(String udf08) {
        this.udf08 = udf08;
    }
    public String getUdf09() {
        return this.udf09;
    }
    
    public void setUdf09(String udf09) {
        this.udf09 = udf09;
    }
    public String getUdf10() {
        return this.udf10;
    }
    
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }
    public String getUdf11() {
        return this.udf11;
    }
    
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }
    public String getUdf12() {
        return this.udf12;
    }
    
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }
    public BigDecimal getUdf57() {
        return this.udf57;
    }
    
    public void setUdf57(BigDecimal udf57) {
        this.udf57 = udf57;
    }
    public BigDecimal getUdf58() {
        return this.udf58;
    }
    
    public void setUdf58(BigDecimal udf58) {
        this.udf58 = udf58;
    }
    public BigDecimal getUdf59() {
        return this.udf59;
    }
    
    public void setUdf59(BigDecimal udf59) {
        this.udf59 = udf59;
    }
    public BigDecimal getUdf60() {
        return this.udf60;
    }
    
    public void setUdf60(BigDecimal udf60) {
        this.udf60 = udf60;
    }
    public BigDecimal getUdf61() {
        return this.udf61;
    }
    
    public void setUdf61(BigDecimal udf61) {
        this.udf61 = udf61;
    }
    public BigDecimal getUdf62() {
        return this.udf62;
    }
    
    public void setUdf62(BigDecimal udf62) {
        this.udf62 = udf62;
    }




}


