package com.edwin.DepartMaterial;
// Generated Jun 23, 2013 8:44:29 AM by Hibernate Tools 3.6.0



/**
 * MocteId generated by hbm2java
 */
public class MocteId  implements java.io.Serializable {


     private String te001;
     private String te002;
     private String te003;

    public MocteId() {
    }

    public MocteId(String te001, String te002, String te003) {
       this.te001 = te001;
       this.te002 = te002;
       this.te003 = te003;
    }
   
    public String getTe001() {
        return this.te001;
    }
    
    public void setTe001(String te001) {
        this.te001 = te001;
    }
    public String getTe002() {
        return this.te002;
    }
    
    public void setTe002(String te002) {
        this.te002 = te002;
    }
    public String getTe003() {
        return this.te003;
    }
    
    public void setTe003(String te003) {
        this.te003 = te003;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MocteId) ) return false;
		 MocteId castOther = ( MocteId ) other; 
         
		 return ( (this.getTe001()==castOther.getTe001()) || ( this.getTe001()!=null && castOther.getTe001()!=null && this.getTe001().equals(castOther.getTe001()) ) )
 && ( (this.getTe002()==castOther.getTe002()) || ( this.getTe002()!=null && castOther.getTe002()!=null && this.getTe002().equals(castOther.getTe002()) ) )
 && ( (this.getTe003()==castOther.getTe003()) || ( this.getTe003()!=null && castOther.getTe003()!=null && this.getTe003().equals(castOther.getTe003()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTe001() == null ? 0 : this.getTe001().hashCode() );
         result = 37 * result + ( getTe002() == null ? 0 : this.getTe002().hashCode() );
         result = 37 * result + ( getTe003() == null ? 0 : this.getTe003().hashCode() );
         return result;
   }   


}


