package com.edwin.DepartMaterial;
// Generated Jun 24, 2013 10:45:01 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * TmpDb generated by hbm2java
 */
public class TmpDb  implements java.io.Serializable {


     private int id;
     private String username;
     private String department;
     private String gdate;
     private Integer randomId;
     private String ph;
     private BigDecimal value;

    public TmpDb() {
    }

	
    public TmpDb(int id) {
        this.id = id;
    }
    public TmpDb(int id, String username, String department, String gdate, Integer randomId, String ph, BigDecimal value) {
       this.id = id;
       this.username = username;
       this.department = department;
       this.gdate = gdate;
       this.randomId = randomId;
       this.ph = ph;
       this.value = value;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getGdate() {
        return this.gdate;
    }
    
    public void setGdate(String gdate) {
        this.gdate = gdate;
    }
    public Integer getRandomId() {
        return this.randomId;
    }
    
    public void setRandomId(Integer randomId) {
        this.randomId = randomId;
    }
    public String getPh() {
        return this.ph;
    }
    
    public void setPh(String ph) {
        this.ph = ph;
    }
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }




}


