/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edwin.warehouse;

import com.edwin.myswingx.CheckBoxEditor;
import com.edwin.myswingx.CheckBoxRenderer;
import javax.swing.JCheckBox;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.windows.TopComponent;

/**
 *
 * @author John
 */
public class SelectBills extends TopComponent  {

    /**
     * Creates new form SelectBills
     */
    public SelectBills() {
        initComponents();
        myDefaultJXTable1.setModel(gs.getTableModel());
        myDefaultJXTable1.getColumn(0).setCellRenderer(new CheckBoxRenderer());
        myDefaultJXTable1.getColumn(0).setCellEditor(new CheckBoxEditor(new JCheckBox()));
        associateLookup(new AbstractLookup(content));

    }

    private GetSfctcModel gs = new GetSfctcModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        myDefaultJXTable1 = new com.edwin.myswingx.MyDefaultJXTable();

        myDefaultJXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        myDefaultJXTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                myDefaultJXTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(myDefaultJXTable1);
        myDefaultJXTable1.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(SelectBills.class, "SelectBills.myDefaultJXTable1.columnModel.title0")); // NOI18N
        myDefaultJXTable1.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(SelectBills.class, "SelectBills.myDefaultJXTable1.columnModel.title1")); // NOI18N
        myDefaultJXTable1.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(SelectBills.class, "SelectBills.myDefaultJXTable1.columnModel.title2")); // NOI18N
        myDefaultJXTable1.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(SelectBills.class, "SelectBills.myDefaultJXTable1.columnModel.title3")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myDefaultJXTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_myDefaultJXTable1PropertyChange
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_myDefaultJXTable1PropertyChange

    private InstanceContent content=new InstanceContent();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.edwin.myswingx.MyDefaultJXTable myDefaultJXTable1;
    // End of variables declaration//GEN-END:variables

}
