/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edwin.my.order;

import org.openide.windows.TopComponentGroup;
import org.openide.windows.WindowManager;

/**
 *
 * @author EDWIN
 */
public class OpenGroup extends javax.swing.JPanel {

    /**
     * Creates new form OpenGroup
     */
    public OpenGroup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isOpened = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(isOpened, org.openide.util.NbBundle.getMessage(OpenGroup.class, "OpenGroup.isOpened.text")); // NOI18N
        isOpened.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isOpenedActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(OpenGroup.class, "OpenGroup.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(isOpened, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(isOpened)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void isOpenedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isOpenedActionPerformed
        // TODO add your handling code here:

        TopComponentGroup group = WindowManager.getDefault().findTopComponentGroup("MyGroup");
        if (group == null) {
            return;
        } else {
            if (isOpened.isSelected()) {
                isOpened.setText("关闭窗口");
                group.open();
            } else {
                isOpened.setText("打开窗口");
                group.close();
            }
    }//GEN-LAST:event_isOpenedActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TopComponentGroup group = WindowManager.getDefault().findTopComponentGroup("MyGroup");
        if (group == null) {
            return;
        } else {
            group.close();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton isOpened;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
