/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edwin.manufacture.inventory;

import com.edwin.myswingx.CheckBoxRenderer;
import com.edwin.myswingx.ComboBoxRenderer;
import com.edwin.myswingx.MyJTableModel;
import java.awt.event.MouseEvent;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.edwin.manufacture.inventory//TransferBillToScrapBill//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "TransferBillToScrapBillTopComponent",
        iconBase = "ICONS/canvas.gif",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "仓库", id = "com.edwin.manufacture.inventory.TransferBillToScrapBillTopComponent")
@ActionReference(path = "Menu/仓库/调拨单转废品入库单" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_TransferBillToScrapBillAction",
        preferredID = "TransferBillToScrapBillTopComponent"
)
@Messages({
    "CTL_TransferBillToScrapBillAction=调拨单转废品入库单",
    "CTL_TransferBillToScrapBillTopComponent=调拨单转废品入库单",
    "HINT_TransferBillToScrapBillTopComponent=This is a TransferBillToScrapBill window"
})
public final class TransferBillToScrapBillTopComponent extends TopComponent {

    public TransferBillToScrapBillTopComponent() {
        initComponents();
        setName(Bundle.CTL_TransferBillToScrapBillTopComponent());
        setToolTipText(Bundle.HINT_TransferBillToScrapBillTopComponent());
        tb_TransferBills.setModel(new MyJTableModel("选中", "单别", "单号").buildModel());
        ((DefaultTableModel) tb_TransferBills.getModel()).addRow(new Vector());
        int checkColumnNumber = 0;
        int billTypeColumnNumber = 1;
        TableColumn checkColumn = jXTable1.getColumnModel().getColumn(checkColumnNumber);
        TableColumn billTypeColumn = jXTable1.getColumnModel().getColumn(billTypeColumnNumber);
        CheckBoxRenderer checkBoxRenderer = new CheckBoxRenderer();
        ComboBoxRenderer comboBoxRenderer = new ComboBoxRenderer();
        checkColumn.setCellRenderer(checkBoxRenderer);
        billTypeColumn.setCellRenderer(comboBoxRenderer);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_TransferBills = new com.edwin.myswingx.MyJXTable();
        btn_GeneraterScrapBill = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();

        tb_TransferBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_TransferBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_TransferBillsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_TransferBills);
        if (tb_TransferBills.getColumnModel().getColumnCount() > 0) {
            tb_TransferBills.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(TransferBillToScrapBillTopComponent.class, "TransferBillToScrapBillTopComponent.tb_TransferBills.columnModel.title0")); // NOI18N
            tb_TransferBills.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(TransferBillToScrapBillTopComponent.class, "TransferBillToScrapBillTopComponent.tb_TransferBills.columnModel.title1")); // NOI18N
            tb_TransferBills.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(TransferBillToScrapBillTopComponent.class, "TransferBillToScrapBillTopComponent.tb_TransferBills.columnModel.title2")); // NOI18N
            tb_TransferBills.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(TransferBillToScrapBillTopComponent.class, "TransferBillToScrapBillTopComponent.tb_TransferBills.columnModel.title3")); // NOI18N
        }

        org.openide.awt.Mnemonics.setLocalizedText(btn_GeneraterScrapBill, org.openide.util.NbBundle.getMessage(TransferBillToScrapBillTopComponent.class, "TransferBillToScrapBillTopComponent.btn_GeneraterScrapBill.text")); // NOI18N
        btn_GeneraterScrapBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GeneraterScrapBillActionPerformed(evt);
            }
        });

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jXTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_GeneraterScrapBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_GeneraterScrapBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GeneraterScrapBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GeneraterScrapBillActionPerformed

    }//GEN-LAST:event_btn_GeneraterScrapBillActionPerformed

    private void tb_TransferBillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_TransferBillsMouseClicked

        if (evt.getButton() == MouseEvent.BUTTON1) {
            int checkColumnNumber = 0;
            int billTypeColumnNumber = 1;
            TableColumn checkColumn = tb_TransferBills.getColumnModel().getColumn(checkColumnNumber);
            TableColumn billTypeColumn = tb_TransferBills.getColumnModel().getColumn(billTypeColumnNumber);
            ((DefaultTableModel) tb_TransferBills.getModel()).addRow(new Vector());
            int sElectedColumnNumber = 0;
            JComboBox cb_billType = new JComboBox();
            JCheckBox jc_check = new JCheckBox();
            jc_check.setSelected(true);
            cb_billType.addItem("1280");
            DefaultCellEditor comboBoxEditor = new DefaultCellEditor(cb_billType);
            CheckBoxRenderer checkBoxRenderer = new CheckBoxRenderer();
            ComboBoxRenderer comboBoxRenderer = new ComboBoxRenderer();
            DefaultCellEditor checkBoxEditor = new DefaultCellEditor(jc_check);
            sElectedColumnNumber = tb_TransferBills.getSelectedColumn();
            if (sElectedColumnNumber == billTypeColumnNumber) {
                billTypeColumn.setCellRenderer(comboBoxRenderer);
                checkColumn.setCellRenderer(checkBoxRenderer);
                checkColumn.setCellEditor(checkBoxEditor);
                billTypeColumn.setCellEditor(comboBoxEditor);
            }
        }
    }//GEN-LAST:event_tb_TransferBillsMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GeneraterScrapBill;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable jXTable1;
    private com.edwin.myswingx.MyJXTable tb_TransferBills;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
