/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edwin.manufacture.inventory;

import com.edwin.myswingx.MyJTableModel;
import javax.swing.table.DefaultTableModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.edwin.manufacture.inventory//TransferBillToScrapBill//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "TransferBillToScrapBillTopComponent",
        iconBase = "ICONS/canvas.gif",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "仓库", id = "com.edwin.manufacture.inventory.TransferBillToScrapBillTopComponent")
@ActionReference(path = "Menu/仓库/调拨单转废品入库单" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_TransferBillToScrapBillAction",
        preferredID = "TransferBillToScrapBillTopComponent"
)
@Messages({
    "CTL_TransferBillToScrapBillAction=调拨单转废品入库单",
    "CTL_TransferBillToScrapBillTopComponent=调拨单转废品入库单",
    "HINT_TransferBillToScrapBillTopComponent=This is a TransferBillToScrapBill window"
})
public final class TransferBillToScrapBillTopComponent extends TopComponent {

    public TransferBillToScrapBillTopComponent() {
        initComponents();
        setName(Bundle.CTL_TransferBillToScrapBillTopComponent());
        setToolTipText(Bundle.HINT_TransferBillToScrapBillTopComponent());
        tb_TransferBills.setModel(new MyJTableModel("选中","单别","单号").buildModel());
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_TransferBills = new com.edwin.myswingx.MyJXTable();
        btn_GeneraterScrapBill = new javax.swing.JButton();

        tb_TransferBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_TransferBills);
        if (tb_TransferBills.getColumnModel().getColumnCount() > 0) {
            tb_TransferBills.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(TransferBillToScrapBillTopComponent.class, "TransferBillToScrapBillTopComponent.tb_TransferBills.columnModel.title0")); // NOI18N
            tb_TransferBills.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(TransferBillToScrapBillTopComponent.class, "TransferBillToScrapBillTopComponent.tb_TransferBills.columnModel.title1")); // NOI18N
            tb_TransferBills.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(TransferBillToScrapBillTopComponent.class, "TransferBillToScrapBillTopComponent.tb_TransferBills.columnModel.title2")); // NOI18N
            tb_TransferBills.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(TransferBillToScrapBillTopComponent.class, "TransferBillToScrapBillTopComponent.tb_TransferBills.columnModel.title3")); // NOI18N
        }

        org.openide.awt.Mnemonics.setLocalizedText(btn_GeneraterScrapBill, org.openide.util.NbBundle.getMessage(TransferBillToScrapBillTopComponent.class, "TransferBillToScrapBillTopComponent.btn_GeneraterScrapBill.text")); // NOI18N
        btn_GeneraterScrapBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GeneraterScrapBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_GeneraterScrapBill)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(btn_GeneraterScrapBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GeneraterScrapBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GeneraterScrapBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_GeneraterScrapBillActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GeneraterScrapBill;
    private javax.swing.JScrollPane jScrollPane1;
    private com.edwin.myswingx.MyJXTable tb_TransferBills;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
