 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edwin.buliao;

import SqlInterface.QueryErp;
import com.edwin.my.RCPSessionFactory;
import com.edwin.myswingx.MyJTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;

/**
 *
 * @author EDWIN
 */
public class BuliaoDetail extends javax.swing.JPanel {

    /**
     * Creates new form BuliaoDetail
     */
    public BuliaoDetail() {
        initComponents();
    }

    public BuliaoDetail(String ph) {
        initComponents();
        jTable6.setModel(new MyJTableModel("领料单别", "领料单号", "领料序号", "领料品号", "领料数量", "工单单别", "工单单号").buildModel());
        jTable1.setModel(new MyJTableModel("工单单别", "工单单号", "工单可领量", "开工日期").buildModel());

        this.ph = ph;
        try {
            setData();
        } catch (ClassNotFoundException ex) {
            Exceptions.printStackTrace(ex);
        } catch (SQLException ex) {
            Exceptions.printStackTrace(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        kckyl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        wslll = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gdkbl = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(BuliaoDetail.class, "BuliaoDetail.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(BuliaoDetail.class, "BuliaoDetail.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(BuliaoDetail.class, "BuliaoDetail.jLabel3.text")); // NOI18N

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable6.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable6.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jTable6);

        kckyl.setText(org.openide.util.NbBundle.getMessage(BuliaoDetail.class, "BuliaoDetail.kckyl.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(BuliaoDetail.class, "BuliaoDetail.jLabel4.text")); // NOI18N

        wslll.setText(org.openide.util.NbBundle.getMessage(BuliaoDetail.class, "BuliaoDetail.wslll.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(BuliaoDetail.class, "BuliaoDetail.jLabel5.text")); // NOI18N

        gdkbl.setText(org.openide.util.NbBundle.getMessage(BuliaoDetail.class, "BuliaoDetail.gdkbl.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane6)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(wslll, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kckyl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gdkbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kckyl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(wslll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gdkbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setData() throws ClassNotFoundException, SQLException {
        List result;
        Session s = RCPSessionFactory.openSession();
        Transaction tx = null;
        tx = s.beginTransaction();
        Query query = s.createSQLQuery("SELECT SUM( CASE WHEN TB005-TB027>=0 THEN (TB004-TB005)-ISNULL(TE005,0) WHEN TB005-TB027<0 THEN (TB004-TB027)-ISNULL(TE005,0) ELSE 0 END ) as TTE\n"
                + "FROM  MOCTB\n"
                + "LEFT JOIN MOCTA ON TB001=TA001 AND TB002=TA002\n"
                + "LEFT JOIN(SELECT ISNULL(SUM(TE005),0) TE005 ,TE004,TE011,TE012 FROM MOCTE  LEFT JOIN MOCTC ON TC001=TE001 AND TC002=TE002 WHERE TC009='N' GROUP BY TE011,TE012,TE004) AS A  ON TE011=MOCTA.TA001 AND TE012=TA002 AND TE004=TB003\n"
                + "WHERE TA013='Y' AND TA011<>'Y' AND TA011<>'y' AND TA011<>'1' AND MOCTA.TA001+MOCTA.TA002 IN(SELECT TC004+TC005 FROM SFCTC WHERE TC004=MOCTA.TA001 AND TC005=MOCTA.TA002 AND TC022='Y')\n"
                + "AND TB003=?  AND TB005<=TB004");
        query.setParameter(0, this.ph);
        result = query.list();
        for (Iterator it = result.iterator(); it.hasNext();) {
            Object ss = it.next();
            gdkbl.setText(ss.toString().trim());
        }
        result.removeAll(result);

        query = s.createSQLQuery(" SELECT ISNULL(SUM(TE005),0)\n"
                + "FROM MOCTE \n"
                + "LEFT JOIN MOCTC ON TC001=TE001 AND TC002=TE002 \n"
                + "WHERE TC009='N' AND TE004=?\n");
        query.setParameter(0, this.ph);
        result = query.list();
        for (Iterator it = result.iterator(); it.hasNext();) {
            Object ss = it.next();
            wslll.setText(ss.toString().trim());
        }
        result.removeAll(result);

        query = s.createSQLQuery("select ISNULL(KYKC,0) KCKBL from V_INVMC_MOCTE_EDWIN where PH=?");
        query.setParameter(0, this.ph);
        result = query.list();
        for (Iterator it = result.iterator(); it.hasNext();) {
            Object ss = it.next();
            kckyl.setText(ss.toString().trim());
        }
        result.removeAll(result);

        tx.commit();
        s.close();

        String kbgdsql = "SELECT TB001,TB002, CASE WHEN TB005-TB027>=0 THEN (TB004-TB005)-ISNULL(TE005,0) WHEN TB005-TB027<0 THEN (TB004-TB027)-ISNULL(TE005,0) ELSE 0 END GDKBL,TA009\n"
                + "FROM  MOCTB\n"
                + "LEFT JOIN MOCTA ON TB001=TA001 AND TB002=TA002\n"
                + "LEFT JOIN(SELECT ISNULL(SUM(TE005),0) TE005 ,TE004,TE011,TE012 FROM MOCTE  LEFT JOIN MOCTC ON TC001=TE001 AND TC002=TE002 WHERE TC009='N' GROUP BY TE011,TE012,TE004) AS A  ON TE011=MOCTA.TA001 AND TE012=TA002 AND TE004=TB003\n"
                + "WHERE TA013='Y' AND TA011<>'Y' AND TA011<>'y' AND TA011<>'1' AND MOCTA.TA001+MOCTA.TA002 IN(SELECT TC004+TC005 FROM SFCTC WHERE TC004=MOCTA.TA001 AND TC005=MOCTA.TA002 AND TC022='Y')\n"
                + "AND TB003=?  \n"
                + "ORDER BY TA009";

        String wslldsql = " SELECT TE001,TE002,TE003,TE004,TE005,TE011,TE012 \n"
                + "	    FROM MOCTE \n"
                + "	    LEFT JOIN MOCTC ON TC001=TE001 AND TC002=TE002 \n"
                + "	    WHERE TC009='N'    AND TE004=?";

        ResultSet rs = null;
        ResultSet rss = null;
        Collection<? extends QueryErp> c = Lookup.getDefault().lookupAll(QueryErp.class);
        Object[] rowData = {null, null, null, null};
        Object[] rowDatam = {null, null, null, null, null, null, null};
        int row = 0;

        ((DefaultTableModel) jTable1.getModel()).setRowCount(0);

        for (QueryErp qr : c) {
            rs = qr.rsErp(kbgdsql, this.ph);
            while (rs.next()) {

                ((DefaultTableModel) jTable1.getModel()).addRow(rowData);
                ArrayList alist = new ArrayList();
                alist.add(rs.getString("TB001"));
                alist.add(rs.getString("TB002"));
                alist.add(rs.getBigDecimal("GDKBL"));
                alist.add(rs.getString("TA009"));

                int column = 0;

                for (Iterator it = alist.iterator(); it.hasNext();) {
                    Object el = it.next();
                    jTable1.setValueAt(el, row, column);
                    column++;
                }
                row++;
                alist.removeAll(alist);
            }

        }

        row = 0;

        ((DefaultTableModel) jTable6.getModel()).setRowCount(0);

        for (QueryErp qr : c) {
            rss = qr.rsErp(wslldsql, this.ph);
            while (rss.next()) {

                ((DefaultTableModel) jTable6.getModel()).addRow(rowDatam);
                ArrayList alist = new ArrayList();
                alist.add(rss.getString("TE001"));
                alist.add(rss.getString("TE002"));
                alist.add(rss.getString("TE003"));
                alist.add(rss.getString("TE004"));
                alist.add(rss.getBigDecimal("TE005"));
                alist.add(rss.getString("TE011"));
                alist.add(rss.getString("TE012"));

                int column = 0;

                for (Iterator it = alist.iterator(); it.hasNext();) {
                    Object el = it.next();
                    jTable6.setValueAt(el, row, column);
                    column++;
                }
                row++;
                alist.removeAll(alist);
            }

        }

        rs.close();
        rss.close();

    }
    private String ph = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gdkbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField kckyl;
    private javax.swing.JTextField wslll;
    // End of variables declaration//GEN-END:variables
}
