package com.edwin.bom;
// Generated Sep 9, 2013 11:12:54 PM by Hibernate Tools 3.6.0



/**
 * BomcbId generated by hbm2java
 */
public class BomcbId  implements java.io.Serializable {


     private String cb002;
     private String cb003;
     private String cb004;

    public BomcbId() {
    }

    public BomcbId(String cb002, String cb003, String cb004) {
       this.cb002 = cb002;
       this.cb003 = cb003;
       this.cb004 = cb004;
    }
   
    public String getCb002() {
        return this.cb002;
    }
    
    public void setCb002(String cb002) {
        this.cb002 = cb002;
    }
    public String getCb003() {
        return this.cb003;
    }
    
    public void setCb003(String cb003) {
        this.cb003 = cb003;
    }
    public String getCb004() {
        return this.cb004;
    }
    
    public void setCb004(String cb004) {
        this.cb004 = cb004;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BomcbId) ) return false;
		 BomcbId castOther = ( BomcbId ) other; 
         
		 return ( (this.getCb002()==castOther.getCb002()) || ( this.getCb002()!=null && castOther.getCb002()!=null && this.getCb002().equals(castOther.getCb002()) ) )
 && ( (this.getCb003()==castOther.getCb003()) || ( this.getCb003()!=null && castOther.getCb003()!=null && this.getCb003().equals(castOther.getCb003()) ) )
 && ( (this.getCb004()==castOther.getCb004()) || ( this.getCb004()!=null && castOther.getCb004()!=null && this.getCb004().equals(castOther.getCb004()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCb002() == null ? 0 : this.getCb002().hashCode() );
         result = 37 * result + ( getCb003() == null ? 0 : this.getCb003().hashCode() );
         result = 37 * result + ( getCb004() == null ? 0 : this.getCb004().hashCode() );
         return result;
   }   


}


