package com.edwin.bom;
// Generated Sep 9, 2013 11:12:54 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Bomcb generated by hbm2java
 */
public class Bomcb  implements java.io.Serializable {


     private BomcbId id;
     private String company;
     private String creator;
     private String usrGroup;
     private String createDate;
     private String modifier;
     private String modiDate;
     private Short flag;
     private String cb001;
     private String cb005;
     private String cb006;
     private String cb007;
     private BigDecimal cb008;
     private Short cb009;
     private BigDecimal cb010;
     private String cb011;
     private Character cb012;
     private String cb013;
     private String cb014;
     private Character cb015;
     private Character cb016;
     private String cb017;
     private String cb018;
     private Character cb019;
     private Short cb020;
     private String cb021;
     private Character cb022;
     private Character cb023;
     private String cb024;
     private String cb025;
     private BigDecimal cb026;
     private BigDecimal cb027;
     private BigDecimal cb028;
     private Character cb029;
     private BigDecimal cb030;
     private Character cb031;
     private Character cb032;
     private BigDecimal cb033;
     private BigDecimal cb034;
     private BigDecimal cb035;
     private String udf01;
     private String udf02;
     private String udf03;
     private String udf04;
     private String udf05;
     private String udf06;
     private BigDecimal udf51;
     private BigDecimal udf52;
     private BigDecimal udf53;
     private BigDecimal udf54;
     private BigDecimal udf55;
     private BigDecimal udf56;
     private String udf07;
     private String udf08;
     private String udf09;
     private String udf10;
     private String udf11;
     private String udf12;
     private BigDecimal udf57;
     private BigDecimal udf58;
     private BigDecimal udf59;
     private BigDecimal udf60;
     private BigDecimal udf61;
     private BigDecimal udf62;

    public Bomcb() {
    }

	
    public Bomcb(BomcbId id) {
        this.id = id;
    }
    public Bomcb(BomcbId id, String company, String creator, String usrGroup, String createDate, String modifier, String modiDate, Short flag, String cb001, String cb005, String cb006, String cb007, BigDecimal cb008, Short cb009, BigDecimal cb010, String cb011, Character cb012, String cb013, String cb014, Character cb015, Character cb016, String cb017, String cb018, Character cb019, Short cb020, String cb021, Character cb022, Character cb023, String cb024, String cb025, BigDecimal cb026, BigDecimal cb027, BigDecimal cb028, Character cb029, BigDecimal cb030, Character cb031, Character cb032, BigDecimal cb033, BigDecimal cb034, BigDecimal cb035, String udf01, String udf02, String udf03, String udf04, String udf05, String udf06, BigDecimal udf51, BigDecimal udf52, BigDecimal udf53, BigDecimal udf54, BigDecimal udf55, BigDecimal udf56, String udf07, String udf08, String udf09, String udf10, String udf11, String udf12, BigDecimal udf57, BigDecimal udf58, BigDecimal udf59, BigDecimal udf60, BigDecimal udf61, BigDecimal udf62) {
       this.id = id;
       this.company = company;
       this.creator = creator;
       this.usrGroup = usrGroup;
       this.createDate = createDate;
       this.modifier = modifier;
       this.modiDate = modiDate;
       this.flag = flag;
       this.cb001 = cb001;
       this.cb005 = cb005;
       this.cb006 = cb006;
       this.cb007 = cb007;
       this.cb008 = cb008;
       this.cb009 = cb009;
       this.cb010 = cb010;
       this.cb011 = cb011;
       this.cb012 = cb012;
       this.cb013 = cb013;
       this.cb014 = cb014;
       this.cb015 = cb015;
       this.cb016 = cb016;
       this.cb017 = cb017;
       this.cb018 = cb018;
       this.cb019 = cb019;
       this.cb020 = cb020;
       this.cb021 = cb021;
       this.cb022 = cb022;
       this.cb023 = cb023;
       this.cb024 = cb024;
       this.cb025 = cb025;
       this.cb026 = cb026;
       this.cb027 = cb027;
       this.cb028 = cb028;
       this.cb029 = cb029;
       this.cb030 = cb030;
       this.cb031 = cb031;
       this.cb032 = cb032;
       this.cb033 = cb033;
       this.cb034 = cb034;
       this.cb035 = cb035;
       this.udf01 = udf01;
       this.udf02 = udf02;
       this.udf03 = udf03;
       this.udf04 = udf04;
       this.udf05 = udf05;
       this.udf06 = udf06;
       this.udf51 = udf51;
       this.udf52 = udf52;
       this.udf53 = udf53;
       this.udf54 = udf54;
       this.udf55 = udf55;
       this.udf56 = udf56;
       this.udf07 = udf07;
       this.udf08 = udf08;
       this.udf09 = udf09;
       this.udf10 = udf10;
       this.udf11 = udf11;
       this.udf12 = udf12;
       this.udf57 = udf57;
       this.udf58 = udf58;
       this.udf59 = udf59;
       this.udf60 = udf60;
       this.udf61 = udf61;
       this.udf62 = udf62;
    }
   
    public BomcbId getId() {
        return this.id;
    }
    
    public void setId(BomcbId id) {
        this.id = id;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public String getUsrGroup() {
        return this.usrGroup;
    }
    
    public void setUsrGroup(String usrGroup) {
        this.usrGroup = usrGroup;
    }
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public String getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(String modiDate) {
        this.modiDate = modiDate;
    }
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }
    public String getCb001() {
        return this.cb001;
    }
    
    public void setCb001(String cb001) {
        this.cb001 = cb001;
    }
    public String getCb005() {
        return this.cb005;
    }
    
    public void setCb005(String cb005) {
        this.cb005 = cb005;
    }
    public String getCb006() {
        return this.cb006;
    }
    
    public void setCb006(String cb006) {
        this.cb006 = cb006;
    }
    public String getCb007() {
        return this.cb007;
    }
    
    public void setCb007(String cb007) {
        this.cb007 = cb007;
    }
    public BigDecimal getCb008() {
        return this.cb008;
    }
    
    public void setCb008(BigDecimal cb008) {
        this.cb008 = cb008;
    }
    public Short getCb009() {
        return this.cb009;
    }
    
    public void setCb009(Short cb009) {
        this.cb009 = cb009;
    }
    public BigDecimal getCb010() {
        return this.cb010;
    }
    
    public void setCb010(BigDecimal cb010) {
        this.cb010 = cb010;
    }
    public String getCb011() {
        return this.cb011;
    }
    
    public void setCb011(String cb011) {
        this.cb011 = cb011;
    }
    public Character getCb012() {
        return this.cb012;
    }
    
    public void setCb012(Character cb012) {
        this.cb012 = cb012;
    }
    public String getCb013() {
        return this.cb013;
    }
    
    public void setCb013(String cb013) {
        this.cb013 = cb013;
    }
    public String getCb014() {
        return this.cb014;
    }
    
    public void setCb014(String cb014) {
        this.cb014 = cb014;
    }
    public Character getCb015() {
        return this.cb015;
    }
    
    public void setCb015(Character cb015) {
        this.cb015 = cb015;
    }
    public Character getCb016() {
        return this.cb016;
    }
    
    public void setCb016(Character cb016) {
        this.cb016 = cb016;
    }
    public String getCb017() {
        return this.cb017;
    }
    
    public void setCb017(String cb017) {
        this.cb017 = cb017;
    }
    public String getCb018() {
        return this.cb018;
    }
    
    public void setCb018(String cb018) {
        this.cb018 = cb018;
    }
    public Character getCb019() {
        return this.cb019;
    }
    
    public void setCb019(Character cb019) {
        this.cb019 = cb019;
    }
    public Short getCb020() {
        return this.cb020;
    }
    
    public void setCb020(Short cb020) {
        this.cb020 = cb020;
    }
    public String getCb021() {
        return this.cb021;
    }
    
    public void setCb021(String cb021) {
        this.cb021 = cb021;
    }
    public Character getCb022() {
        return this.cb022;
    }
    
    public void setCb022(Character cb022) {
        this.cb022 = cb022;
    }
    public Character getCb023() {
        return this.cb023;
    }
    
    public void setCb023(Character cb023) {
        this.cb023 = cb023;
    }
    public String getCb024() {
        return this.cb024;
    }
    
    public void setCb024(String cb024) {
        this.cb024 = cb024;
    }
    public String getCb025() {
        return this.cb025;
    }
    
    public void setCb025(String cb025) {
        this.cb025 = cb025;
    }
    public BigDecimal getCb026() {
        return this.cb026;
    }
    
    public void setCb026(BigDecimal cb026) {
        this.cb026 = cb026;
    }
    public BigDecimal getCb027() {
        return this.cb027;
    }
    
    public void setCb027(BigDecimal cb027) {
        this.cb027 = cb027;
    }
    public BigDecimal getCb028() {
        return this.cb028;
    }
    
    public void setCb028(BigDecimal cb028) {
        this.cb028 = cb028;
    }
    public Character getCb029() {
        return this.cb029;
    }
    
    public void setCb029(Character cb029) {
        this.cb029 = cb029;
    }
    public BigDecimal getCb030() {
        return this.cb030;
    }
    
    public void setCb030(BigDecimal cb030) {
        this.cb030 = cb030;
    }
    public Character getCb031() {
        return this.cb031;
    }
    
    public void setCb031(Character cb031) {
        this.cb031 = cb031;
    }
    public Character getCb032() {
        return this.cb032;
    }
    
    public void setCb032(Character cb032) {
        this.cb032 = cb032;
    }
    public BigDecimal getCb033() {
        return this.cb033;
    }
    
    public void setCb033(BigDecimal cb033) {
        this.cb033 = cb033;
    }
    public BigDecimal getCb034() {
        return this.cb034;
    }
    
    public void setCb034(BigDecimal cb034) {
        this.cb034 = cb034;
    }
    public BigDecimal getCb035() {
        return this.cb035;
    }
    
    public void setCb035(BigDecimal cb035) {
        this.cb035 = cb035;
    }
    public String getUdf01() {
        return this.udf01;
    }
    
    public void setUdf01(String udf01) {
        this.udf01 = udf01;
    }
    public String getUdf02() {
        return this.udf02;
    }
    
    public void setUdf02(String udf02) {
        this.udf02 = udf02;
    }
    public String getUdf03() {
        return this.udf03;
    }
    
    public void setUdf03(String udf03) {
        this.udf03 = udf03;
    }
    public String getUdf04() {
        return this.udf04;
    }
    
    public void setUdf04(String udf04) {
        this.udf04 = udf04;
    }
    public String getUdf05() {
        return this.udf05;
    }
    
    public void setUdf05(String udf05) {
        this.udf05 = udf05;
    }
    public String getUdf06() {
        return this.udf06;
    }
    
    public void setUdf06(String udf06) {
        this.udf06 = udf06;
    }
    public BigDecimal getUdf51() {
        return this.udf51;
    }
    
    public void setUdf51(BigDecimal udf51) {
        this.udf51 = udf51;
    }
    public BigDecimal getUdf52() {
        return this.udf52;
    }
    
    public void setUdf52(BigDecimal udf52) {
        this.udf52 = udf52;
    }
    public BigDecimal getUdf53() {
        return this.udf53;
    }
    
    public void setUdf53(BigDecimal udf53) {
        this.udf53 = udf53;
    }
    public BigDecimal getUdf54() {
        return this.udf54;
    }
    
    public void setUdf54(BigDecimal udf54) {
        this.udf54 = udf54;
    }
    public BigDecimal getUdf55() {
        return this.udf55;
    }
    
    public void setUdf55(BigDecimal udf55) {
        this.udf55 = udf55;
    }
    public BigDecimal getUdf56() {
        return this.udf56;
    }
    
    public void setUdf56(BigDecimal udf56) {
        this.udf56 = udf56;
    }
    public String getUdf07() {
        return this.udf07;
    }
    
    public void setUdf07(String udf07) {
        this.udf07 = udf07;
    }
    public String getUdf08() {
        return this.udf08;
    }
    
    public void setUdf08(String udf08) {
        this.udf08 = udf08;
    }
    public String getUdf09() {
        return this.udf09;
    }
    
    public void setUdf09(String udf09) {
        this.udf09 = udf09;
    }
    public String getUdf10() {
        return this.udf10;
    }
    
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }
    public String getUdf11() {
        return this.udf11;
    }
    
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }
    public String getUdf12() {
        return this.udf12;
    }
    
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }
    public BigDecimal getUdf57() {
        return this.udf57;
    }
    
    public void setUdf57(BigDecimal udf57) {
        this.udf57 = udf57;
    }
    public BigDecimal getUdf58() {
        return this.udf58;
    }
    
    public void setUdf58(BigDecimal udf58) {
        this.udf58 = udf58;
    }
    public BigDecimal getUdf59() {
        return this.udf59;
    }
    
    public void setUdf59(BigDecimal udf59) {
        this.udf59 = udf59;
    }
    public BigDecimal getUdf60() {
        return this.udf60;
    }
    
    public void setUdf60(BigDecimal udf60) {
        this.udf60 = udf60;
    }
    public BigDecimal getUdf61() {
        return this.udf61;
    }
    
    public void setUdf61(BigDecimal udf61) {
        this.udf61 = udf61;
    }
    public BigDecimal getUdf62() {
        return this.udf62;
    }
    
    public void setUdf62(BigDecimal udf62) {
        this.udf62 = udf62;
    }




}


