package com.edwin.bom;
// Generated Sep 9, 2013 11:12:54 PM by Hibernate Tools 3.6.0



/**
 * BomcaId generated by hbm2java
 */
public class BomcaId  implements java.io.Serializable {


     private String ca001;
     private String ca002;

    public BomcaId() {
    }

    public BomcaId(String ca001, String ca002) {
       this.ca001 = ca001;
       this.ca002 = ca002;
    }
   
    public String getCa001() {
        return this.ca001;
    }
    
    public void setCa001(String ca001) {
        this.ca001 = ca001;
    }
    public String getCa002() {
        return this.ca002;
    }
    
    public void setCa002(String ca002) {
        this.ca002 = ca002;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BomcaId) ) return false;
		 BomcaId castOther = ( BomcaId ) other; 
         
		 return ( (this.getCa001()==castOther.getCa001()) || ( this.getCa001()!=null && castOther.getCa001()!=null && this.getCa001().equals(castOther.getCa001()) ) )
 && ( (this.getCa002()==castOther.getCa002()) || ( this.getCa002()!=null && castOther.getCa002()!=null && this.getCa002().equals(castOther.getCa002()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCa001() == null ? 0 : this.getCa001().hashCode() );
         result = 37 * result + ( getCa002() == null ? 0 : this.getCa002().hashCode() );
         return result;
   }   


}


