package com.edwin.bom;
// Generated Sep 9, 2013 11:12:54 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * BommpId generated by hbm2java
 */
public class BommpId  implements java.io.Serializable {


     private String mp001;
     private String mp002;
     private String mp003;
     private BigDecimal mp004;

    public BommpId() {
    }

    public BommpId(String mp001, String mp002, String mp003, BigDecimal mp004) {
       this.mp001 = mp001;
       this.mp002 = mp002;
       this.mp003 = mp003;
       this.mp004 = mp004;
    }
   
    public String getMp001() {
        return this.mp001;
    }
    
    public void setMp001(String mp001) {
        this.mp001 = mp001;
    }
    public String getMp002() {
        return this.mp002;
    }
    
    public void setMp002(String mp002) {
        this.mp002 = mp002;
    }
    public String getMp003() {
        return this.mp003;
    }
    
    public void setMp003(String mp003) {
        this.mp003 = mp003;
    }
    public BigDecimal getMp004() {
        return this.mp004;
    }
    
    public void setMp004(BigDecimal mp004) {
        this.mp004 = mp004;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BommpId) ) return false;
		 BommpId castOther = ( BommpId ) other; 
         
		 return ( (this.getMp001()==castOther.getMp001()) || ( this.getMp001()!=null && castOther.getMp001()!=null && this.getMp001().equals(castOther.getMp001()) ) )
 && ( (this.getMp002()==castOther.getMp002()) || ( this.getMp002()!=null && castOther.getMp002()!=null && this.getMp002().equals(castOther.getMp002()) ) )
 && ( (this.getMp003()==castOther.getMp003()) || ( this.getMp003()!=null && castOther.getMp003()!=null && this.getMp003().equals(castOther.getMp003()) ) )
 && ( (this.getMp004()==castOther.getMp004()) || ( this.getMp004()!=null && castOther.getMp004()!=null && this.getMp004().equals(castOther.getMp004()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMp001() == null ? 0 : this.getMp001().hashCode() );
         result = 37 * result + ( getMp002() == null ? 0 : this.getMp002().hashCode() );
         result = 37 * result + ( getMp003() == null ? 0 : this.getMp003().hashCode() );
         result = 37 * result + ( getMp004() == null ? 0 : this.getMp004().hashCode() );
         return result;
   }   


}


