package com.edwin.bom;
// Generated Sep 9, 2013 11:12:54 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Bommc generated by hbm2java
 */
public class Bommc  implements java.io.Serializable {


     private String mc001;
     private String company;
     private String creator;
     private String usrGroup;
     private String createDate;
     private String modifier;
     private String modiDate;
     private Short flag;
     private String mc002;
     private String mc003;
     private BigDecimal mc004;
     private String mc005;
     private String mc006;
     private String mc007;
     private String mc008;
     private String mc009;
     private String mc010;
     private Character mc011;
     private String mc012;
     private String mc013;
     private BigDecimal mc014;
     private BigDecimal mc015;
     private BigDecimal mc016;
     private Character mc017;
     private Character mc018;
     private Character mc019;
     private BigDecimal mc020;
     private String udf01;
     private String udf02;
     private String udf03;
     private String udf04;
     private String udf05;
     private String udf06;
     private BigDecimal udf51;
     private BigDecimal udf52;
     private BigDecimal udf53;
     private BigDecimal udf54;
     private BigDecimal udf55;
     private BigDecimal udf56;
     private String udf07;
     private String udf08;
     private String udf09;
     private String udf10;
     private String udf11;
     private String udf12;
     private BigDecimal udf57;
     private BigDecimal udf58;
     private BigDecimal udf59;
     private BigDecimal udf60;
     private BigDecimal udf61;
     private BigDecimal udf62;

    public Bommc() {
    }

	
    public Bommc(String mc001) {
        this.mc001 = mc001;
    }
    public Bommc(String mc001, String company, String creator, String usrGroup, String createDate, String modifier, String modiDate, Short flag, String mc002, String mc003, BigDecimal mc004, String mc005, String mc006, String mc007, String mc008, String mc009, String mc010, Character mc011, String mc012, String mc013, BigDecimal mc014, BigDecimal mc015, BigDecimal mc016, Character mc017, Character mc018, Character mc019, BigDecimal mc020, String udf01, String udf02, String udf03, String udf04, String udf05, String udf06, BigDecimal udf51, BigDecimal udf52, BigDecimal udf53, BigDecimal udf54, BigDecimal udf55, BigDecimal udf56, String udf07, String udf08, String udf09, String udf10, String udf11, String udf12, BigDecimal udf57, BigDecimal udf58, BigDecimal udf59, BigDecimal udf60, BigDecimal udf61, BigDecimal udf62) {
       this.mc001 = mc001;
       this.company = company;
       this.creator = creator;
       this.usrGroup = usrGroup;
       this.createDate = createDate;
       this.modifier = modifier;
       this.modiDate = modiDate;
       this.flag = flag;
       this.mc002 = mc002;
       this.mc003 = mc003;
       this.mc004 = mc004;
       this.mc005 = mc005;
       this.mc006 = mc006;
       this.mc007 = mc007;
       this.mc008 = mc008;
       this.mc009 = mc009;
       this.mc010 = mc010;
       this.mc011 = mc011;
       this.mc012 = mc012;
       this.mc013 = mc013;
       this.mc014 = mc014;
       this.mc015 = mc015;
       this.mc016 = mc016;
       this.mc017 = mc017;
       this.mc018 = mc018;
       this.mc019 = mc019;
       this.mc020 = mc020;
       this.udf01 = udf01;
       this.udf02 = udf02;
       this.udf03 = udf03;
       this.udf04 = udf04;
       this.udf05 = udf05;
       this.udf06 = udf06;
       this.udf51 = udf51;
       this.udf52 = udf52;
       this.udf53 = udf53;
       this.udf54 = udf54;
       this.udf55 = udf55;
       this.udf56 = udf56;
       this.udf07 = udf07;
       this.udf08 = udf08;
       this.udf09 = udf09;
       this.udf10 = udf10;
       this.udf11 = udf11;
       this.udf12 = udf12;
       this.udf57 = udf57;
       this.udf58 = udf58;
       this.udf59 = udf59;
       this.udf60 = udf60;
       this.udf61 = udf61;
       this.udf62 = udf62;
    }
   
    public String getMc001() {
        return this.mc001;
    }
    
    public void setMc001(String mc001) {
        this.mc001 = mc001;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public String getUsrGroup() {
        return this.usrGroup;
    }
    
    public void setUsrGroup(String usrGroup) {
        this.usrGroup = usrGroup;
    }
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public String getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(String modiDate) {
        this.modiDate = modiDate;
    }
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }
    public String getMc002() {
        return this.mc002;
    }
    
    public void setMc002(String mc002) {
        this.mc002 = mc002;
    }
    public String getMc003() {
        return this.mc003;
    }
    
    public void setMc003(String mc003) {
        this.mc003 = mc003;
    }
    public BigDecimal getMc004() {
        return this.mc004;
    }
    
    public void setMc004(BigDecimal mc004) {
        this.mc004 = mc004;
    }
    public String getMc005() {
        return this.mc005;
    }
    
    public void setMc005(String mc005) {
        this.mc005 = mc005;
    }
    public String getMc006() {
        return this.mc006;
    }
    
    public void setMc006(String mc006) {
        this.mc006 = mc006;
    }
    public String getMc007() {
        return this.mc007;
    }
    
    public void setMc007(String mc007) {
        this.mc007 = mc007;
    }
    public String getMc008() {
        return this.mc008;
    }
    
    public void setMc008(String mc008) {
        this.mc008 = mc008;
    }
    public String getMc009() {
        return this.mc009;
    }
    
    public void setMc009(String mc009) {
        this.mc009 = mc009;
    }
    public String getMc010() {
        return this.mc010;
    }
    
    public void setMc010(String mc010) {
        this.mc010 = mc010;
    }
    public Character getMc011() {
        return this.mc011;
    }
    
    public void setMc011(Character mc011) {
        this.mc011 = mc011;
    }
    public String getMc012() {
        return this.mc012;
    }
    
    public void setMc012(String mc012) {
        this.mc012 = mc012;
    }
    public String getMc013() {
        return this.mc013;
    }
    
    public void setMc013(String mc013) {
        this.mc013 = mc013;
    }
    public BigDecimal getMc014() {
        return this.mc014;
    }
    
    public void setMc014(BigDecimal mc014) {
        this.mc014 = mc014;
    }
    public BigDecimal getMc015() {
        return this.mc015;
    }
    
    public void setMc015(BigDecimal mc015) {
        this.mc015 = mc015;
    }
    public BigDecimal getMc016() {
        return this.mc016;
    }
    
    public void setMc016(BigDecimal mc016) {
        this.mc016 = mc016;
    }
    public Character getMc017() {
        return this.mc017;
    }
    
    public void setMc017(Character mc017) {
        this.mc017 = mc017;
    }
    public Character getMc018() {
        return this.mc018;
    }
    
    public void setMc018(Character mc018) {
        this.mc018 = mc018;
    }
    public Character getMc019() {
        return this.mc019;
    }
    
    public void setMc019(Character mc019) {
        this.mc019 = mc019;
    }
    public BigDecimal getMc020() {
        return this.mc020;
    }
    
    public void setMc020(BigDecimal mc020) {
        this.mc020 = mc020;
    }
    public String getUdf01() {
        return this.udf01;
    }
    
    public void setUdf01(String udf01) {
        this.udf01 = udf01;
    }
    public String getUdf02() {
        return this.udf02;
    }
    
    public void setUdf02(String udf02) {
        this.udf02 = udf02;
    }
    public String getUdf03() {
        return this.udf03;
    }
    
    public void setUdf03(String udf03) {
        this.udf03 = udf03;
    }
    public String getUdf04() {
        return this.udf04;
    }
    
    public void setUdf04(String udf04) {
        this.udf04 = udf04;
    }
    public String getUdf05() {
        return this.udf05;
    }
    
    public void setUdf05(String udf05) {
        this.udf05 = udf05;
    }
    public String getUdf06() {
        return this.udf06;
    }
    
    public void setUdf06(String udf06) {
        this.udf06 = udf06;
    }
    public BigDecimal getUdf51() {
        return this.udf51;
    }
    
    public void setUdf51(BigDecimal udf51) {
        this.udf51 = udf51;
    }
    public BigDecimal getUdf52() {
        return this.udf52;
    }
    
    public void setUdf52(BigDecimal udf52) {
        this.udf52 = udf52;
    }
    public BigDecimal getUdf53() {
        return this.udf53;
    }
    
    public void setUdf53(BigDecimal udf53) {
        this.udf53 = udf53;
    }
    public BigDecimal getUdf54() {
        return this.udf54;
    }
    
    public void setUdf54(BigDecimal udf54) {
        this.udf54 = udf54;
    }
    public BigDecimal getUdf55() {
        return this.udf55;
    }
    
    public void setUdf55(BigDecimal udf55) {
        this.udf55 = udf55;
    }
    public BigDecimal getUdf56() {
        return this.udf56;
    }
    
    public void setUdf56(BigDecimal udf56) {
        this.udf56 = udf56;
    }
    public String getUdf07() {
        return this.udf07;
    }
    
    public void setUdf07(String udf07) {
        this.udf07 = udf07;
    }
    public String getUdf08() {
        return this.udf08;
    }
    
    public void setUdf08(String udf08) {
        this.udf08 = udf08;
    }
    public String getUdf09() {
        return this.udf09;
    }
    
    public void setUdf09(String udf09) {
        this.udf09 = udf09;
    }
    public String getUdf10() {
        return this.udf10;
    }
    
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }
    public String getUdf11() {
        return this.udf11;
    }
    
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }
    public String getUdf12() {
        return this.udf12;
    }
    
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }
    public BigDecimal getUdf57() {
        return this.udf57;
    }
    
    public void setUdf57(BigDecimal udf57) {
        this.udf57 = udf57;
    }
    public BigDecimal getUdf58() {
        return this.udf58;
    }
    
    public void setUdf58(BigDecimal udf58) {
        this.udf58 = udf58;
    }
    public BigDecimal getUdf59() {
        return this.udf59;
    }
    
    public void setUdf59(BigDecimal udf59) {
        this.udf59 = udf59;
    }
    public BigDecimal getUdf60() {
        return this.udf60;
    }
    
    public void setUdf60(BigDecimal udf60) {
        this.udf60 = udf60;
    }
    public BigDecimal getUdf61() {
        return this.udf61;
    }
    
    public void setUdf61(BigDecimal udf61) {
        this.udf61 = udf61;
    }
    public BigDecimal getUdf62() {
        return this.udf62;
    }
    
    public void setUdf62(BigDecimal udf62) {
        this.udf62 = udf62;
    }




}


