package com.edwin.bom;
// Generated Sep 9, 2013 11:12:54 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Bommd generated by hbm2java
 */
public class Bommd  implements java.io.Serializable {


     private BommdId id;
     private String company;
     private String creator;
     private String usrGroup;
     private String createDate;
     private String modifier;
     private String modiDate;
     private Short flag;
     private String md003;
     private String md004;
     private String md005;
     private BigDecimal md006;
     private Short md007;
     private BigDecimal md008;
     private String md009;
     private Character md010;
     private String md011;
     private String md012;
     private Character md013;
     private Character md014;
     private String md015;
     private String md016;
     private Character md017;
     private Short md018;
     private String md019;
     private String md020;
     private String md021;
     private String md022;
     private String md023;
     private Character md024;
     private String md025;
     private String md026;
     private BigDecimal md027;
     private BigDecimal md028;
     private BigDecimal md029;
     private String mdc01;
     private Character mdc02;
     private BigDecimal md030;
     private Character md031;
     private Character md032;
     private BigDecimal md033;
     private BigDecimal md034;
     private BigDecimal md035;
     private String udf01;
     private String udf02;
     private String udf03;
     private String udf04;
     private String udf05;
     private String udf06;
     private BigDecimal udf51;
     private BigDecimal udf52;
     private BigDecimal udf53;
     private BigDecimal udf54;
     private BigDecimal udf55;
     private BigDecimal udf56;
     private String udf07;
     private String udf08;
     private String udf09;
     private String udf10;
     private String udf11;
     private String udf12;
     private BigDecimal udf57;
     private BigDecimal udf58;
     private BigDecimal udf59;
     private BigDecimal udf60;
     private BigDecimal udf61;
     private BigDecimal udf62;

    public Bommd() {
    }

	
    public Bommd(BommdId id) {
        this.id = id;
    }
    public Bommd(BommdId id, String company, String creator, String usrGroup, String createDate, String modifier, String modiDate, Short flag, String md003, String md004, String md005, BigDecimal md006, Short md007, BigDecimal md008, String md009, Character md010, String md011, String md012, Character md013, Character md014, String md015, String md016, Character md017, Short md018, String md019, String md020, String md021, String md022, String md023, Character md024, String md025, String md026, BigDecimal md027, BigDecimal md028, BigDecimal md029, String mdc01, Character mdc02, BigDecimal md030, Character md031, Character md032, BigDecimal md033, BigDecimal md034, BigDecimal md035, String udf01, String udf02, String udf03, String udf04, String udf05, String udf06, BigDecimal udf51, BigDecimal udf52, BigDecimal udf53, BigDecimal udf54, BigDecimal udf55, BigDecimal udf56, String udf07, String udf08, String udf09, String udf10, String udf11, String udf12, BigDecimal udf57, BigDecimal udf58, BigDecimal udf59, BigDecimal udf60, BigDecimal udf61, BigDecimal udf62) {
       this.id = id;
       this.company = company;
       this.creator = creator;
       this.usrGroup = usrGroup;
       this.createDate = createDate;
       this.modifier = modifier;
       this.modiDate = modiDate;
       this.flag = flag;
       this.md003 = md003;
       this.md004 = md004;
       this.md005 = md005;
       this.md006 = md006;
       this.md007 = md007;
       this.md008 = md008;
       this.md009 = md009;
       this.md010 = md010;
       this.md011 = md011;
       this.md012 = md012;
       this.md013 = md013;
       this.md014 = md014;
       this.md015 = md015;
       this.md016 = md016;
       this.md017 = md017;
       this.md018 = md018;
       this.md019 = md019;
       this.md020 = md020;
       this.md021 = md021;
       this.md022 = md022;
       this.md023 = md023;
       this.md024 = md024;
       this.md025 = md025;
       this.md026 = md026;
       this.md027 = md027;
       this.md028 = md028;
       this.md029 = md029;
       this.mdc01 = mdc01;
       this.mdc02 = mdc02;
       this.md030 = md030;
       this.md031 = md031;
       this.md032 = md032;
       this.md033 = md033;
       this.md034 = md034;
       this.md035 = md035;
       this.udf01 = udf01;
       this.udf02 = udf02;
       this.udf03 = udf03;
       this.udf04 = udf04;
       this.udf05 = udf05;
       this.udf06 = udf06;
       this.udf51 = udf51;
       this.udf52 = udf52;
       this.udf53 = udf53;
       this.udf54 = udf54;
       this.udf55 = udf55;
       this.udf56 = udf56;
       this.udf07 = udf07;
       this.udf08 = udf08;
       this.udf09 = udf09;
       this.udf10 = udf10;
       this.udf11 = udf11;
       this.udf12 = udf12;
       this.udf57 = udf57;
       this.udf58 = udf58;
       this.udf59 = udf59;
       this.udf60 = udf60;
       this.udf61 = udf61;
       this.udf62 = udf62;
    }
   
    public BommdId getId() {
        return this.id;
    }
    
    public void setId(BommdId id) {
        this.id = id;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public String getUsrGroup() {
        return this.usrGroup;
    }
    
    public void setUsrGroup(String usrGroup) {
        this.usrGroup = usrGroup;
    }
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public String getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(String modiDate) {
        this.modiDate = modiDate;
    }
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }
    public String getMd003() {
        return this.md003;
    }
    
    public void setMd003(String md003) {
        this.md003 = md003;
    }
    public String getMd004() {
        return this.md004;
    }
    
    public void setMd004(String md004) {
        this.md004 = md004;
    }
    public String getMd005() {
        return this.md005;
    }
    
    public void setMd005(String md005) {
        this.md005 = md005;
    }
    public BigDecimal getMd006() {
        return this.md006;
    }
    
    public void setMd006(BigDecimal md006) {
        this.md006 = md006;
    }
    public Short getMd007() {
        return this.md007;
    }
    
    public void setMd007(Short md007) {
        this.md007 = md007;
    }
    public BigDecimal getMd008() {
        return this.md008;
    }
    
    public void setMd008(BigDecimal md008) {
        this.md008 = md008;
    }
    public String getMd009() {
        return this.md009;
    }
    
    public void setMd009(String md009) {
        this.md009 = md009;
    }
    public Character getMd010() {
        return this.md010;
    }
    
    public void setMd010(Character md010) {
        this.md010 = md010;
    }
    public String getMd011() {
        return this.md011;
    }
    
    public void setMd011(String md011) {
        this.md011 = md011;
    }
    public String getMd012() {
        return this.md012;
    }
    
    public void setMd012(String md012) {
        this.md012 = md012;
    }
    public Character getMd013() {
        return this.md013;
    }
    
    public void setMd013(Character md013) {
        this.md013 = md013;
    }
    public Character getMd014() {
        return this.md014;
    }
    
    public void setMd014(Character md014) {
        this.md014 = md014;
    }
    public String getMd015() {
        return this.md015;
    }
    
    public void setMd015(String md015) {
        this.md015 = md015;
    }
    public String getMd016() {
        return this.md016;
    }
    
    public void setMd016(String md016) {
        this.md016 = md016;
    }
    public Character getMd017() {
        return this.md017;
    }
    
    public void setMd017(Character md017) {
        this.md017 = md017;
    }
    public Short getMd018() {
        return this.md018;
    }
    
    public void setMd018(Short md018) {
        this.md018 = md018;
    }
    public String getMd019() {
        return this.md019;
    }
    
    public void setMd019(String md019) {
        this.md019 = md019;
    }
    public String getMd020() {
        return this.md020;
    }
    
    public void setMd020(String md020) {
        this.md020 = md020;
    }
    public String getMd021() {
        return this.md021;
    }
    
    public void setMd021(String md021) {
        this.md021 = md021;
    }
    public String getMd022() {
        return this.md022;
    }
    
    public void setMd022(String md022) {
        this.md022 = md022;
    }
    public String getMd023() {
        return this.md023;
    }
    
    public void setMd023(String md023) {
        this.md023 = md023;
    }
    public Character getMd024() {
        return this.md024;
    }
    
    public void setMd024(Character md024) {
        this.md024 = md024;
    }
    public String getMd025() {
        return this.md025;
    }
    
    public void setMd025(String md025) {
        this.md025 = md025;
    }
    public String getMd026() {
        return this.md026;
    }
    
    public void setMd026(String md026) {
        this.md026 = md026;
    }
    public BigDecimal getMd027() {
        return this.md027;
    }
    
    public void setMd027(BigDecimal md027) {
        this.md027 = md027;
    }
    public BigDecimal getMd028() {
        return this.md028;
    }
    
    public void setMd028(BigDecimal md028) {
        this.md028 = md028;
    }
    public BigDecimal getMd029() {
        return this.md029;
    }
    
    public void setMd029(BigDecimal md029) {
        this.md029 = md029;
    }
    public String getMdc01() {
        return this.mdc01;
    }
    
    public void setMdc01(String mdc01) {
        this.mdc01 = mdc01;
    }
    public Character getMdc02() {
        return this.mdc02;
    }
    
    public void setMdc02(Character mdc02) {
        this.mdc02 = mdc02;
    }
    public BigDecimal getMd030() {
        return this.md030;
    }
    
    public void setMd030(BigDecimal md030) {
        this.md030 = md030;
    }
    public Character getMd031() {
        return this.md031;
    }
    
    public void setMd031(Character md031) {
        this.md031 = md031;
    }
    public Character getMd032() {
        return this.md032;
    }
    
    public void setMd032(Character md032) {
        this.md032 = md032;
    }
    public BigDecimal getMd033() {
        return this.md033;
    }
    
    public void setMd033(BigDecimal md033) {
        this.md033 = md033;
    }
    public BigDecimal getMd034() {
        return this.md034;
    }
    
    public void setMd034(BigDecimal md034) {
        this.md034 = md034;
    }
    public BigDecimal getMd035() {
        return this.md035;
    }
    
    public void setMd035(BigDecimal md035) {
        this.md035 = md035;
    }
    public String getUdf01() {
        return this.udf01;
    }
    
    public void setUdf01(String udf01) {
        this.udf01 = udf01;
    }
    public String getUdf02() {
        return this.udf02;
    }
    
    public void setUdf02(String udf02) {
        this.udf02 = udf02;
    }
    public String getUdf03() {
        return this.udf03;
    }
    
    public void setUdf03(String udf03) {
        this.udf03 = udf03;
    }
    public String getUdf04() {
        return this.udf04;
    }
    
    public void setUdf04(String udf04) {
        this.udf04 = udf04;
    }
    public String getUdf05() {
        return this.udf05;
    }
    
    public void setUdf05(String udf05) {
        this.udf05 = udf05;
    }
    public String getUdf06() {
        return this.udf06;
    }
    
    public void setUdf06(String udf06) {
        this.udf06 = udf06;
    }
    public BigDecimal getUdf51() {
        return this.udf51;
    }
    
    public void setUdf51(BigDecimal udf51) {
        this.udf51 = udf51;
    }
    public BigDecimal getUdf52() {
        return this.udf52;
    }
    
    public void setUdf52(BigDecimal udf52) {
        this.udf52 = udf52;
    }
    public BigDecimal getUdf53() {
        return this.udf53;
    }
    
    public void setUdf53(BigDecimal udf53) {
        this.udf53 = udf53;
    }
    public BigDecimal getUdf54() {
        return this.udf54;
    }
    
    public void setUdf54(BigDecimal udf54) {
        this.udf54 = udf54;
    }
    public BigDecimal getUdf55() {
        return this.udf55;
    }
    
    public void setUdf55(BigDecimal udf55) {
        this.udf55 = udf55;
    }
    public BigDecimal getUdf56() {
        return this.udf56;
    }
    
    public void setUdf56(BigDecimal udf56) {
        this.udf56 = udf56;
    }
    public String getUdf07() {
        return this.udf07;
    }
    
    public void setUdf07(String udf07) {
        this.udf07 = udf07;
    }
    public String getUdf08() {
        return this.udf08;
    }
    
    public void setUdf08(String udf08) {
        this.udf08 = udf08;
    }
    public String getUdf09() {
        return this.udf09;
    }
    
    public void setUdf09(String udf09) {
        this.udf09 = udf09;
    }
    public String getUdf10() {
        return this.udf10;
    }
    
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }
    public String getUdf11() {
        return this.udf11;
    }
    
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }
    public String getUdf12() {
        return this.udf12;
    }
    
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }
    public BigDecimal getUdf57() {
        return this.udf57;
    }
    
    public void setUdf57(BigDecimal udf57) {
        this.udf57 = udf57;
    }
    public BigDecimal getUdf58() {
        return this.udf58;
    }
    
    public void setUdf58(BigDecimal udf58) {
        this.udf58 = udf58;
    }
    public BigDecimal getUdf59() {
        return this.udf59;
    }
    
    public void setUdf59(BigDecimal udf59) {
        this.udf59 = udf59;
    }
    public BigDecimal getUdf60() {
        return this.udf60;
    }
    
    public void setUdf60(BigDecimal udf60) {
        this.udf60 = udf60;
    }
    public BigDecimal getUdf61() {
        return this.udf61;
    }
    
    public void setUdf61(BigDecimal udf61) {
        this.udf61 = udf61;
    }
    public BigDecimal getUdf62() {
        return this.udf62;
    }
    
    public void setUdf62(BigDecimal udf62) {
        this.udf62 = udf62;
    }




}


