package com.edwin.bom;
// Generated Sep 9, 2013 11:12:54 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Coptv generated by hbm2java
 */
public class Coptv  implements java.io.Serializable {


     private CoptvId id;
     private String company;
     private String creator;
     private String usrGroup;
     private String createDate;
     private String modifier;
     private String modiDate;
     private Short flag;
     private BigDecimal tv005;
     private BigDecimal tv006;
     private String tv007;
     private Character tv008;
     private String tv009;
     private String tv010;
     private BigDecimal tv011;
     private BigDecimal tv012;
     private BigDecimal tv013;
     private String udf01;
     private String udf02;
     private String udf03;
     private String udf04;
     private String udf05;
     private String udf06;
     private BigDecimal udf51;
     private BigDecimal udf52;
     private BigDecimal udf53;
     private BigDecimal udf54;
     private BigDecimal udf55;
     private BigDecimal udf56;
     private String udf07;
     private String udf08;
     private String udf09;
     private String udf10;
     private String udf11;
     private String udf12;
     private BigDecimal udf57;
     private BigDecimal udf58;
     private BigDecimal udf59;
     private BigDecimal udf60;
     private BigDecimal udf61;
     private BigDecimal udf62;

    public Coptv() {
    }

	
    public Coptv(CoptvId id) {
        this.id = id;
    }
    public Coptv(CoptvId id, String company, String creator, String usrGroup, String createDate, String modifier, String modiDate, Short flag, BigDecimal tv005, BigDecimal tv006, String tv007, Character tv008, String tv009, String tv010, BigDecimal tv011, BigDecimal tv012, BigDecimal tv013, String udf01, String udf02, String udf03, String udf04, String udf05, String udf06, BigDecimal udf51, BigDecimal udf52, BigDecimal udf53, BigDecimal udf54, BigDecimal udf55, BigDecimal udf56, String udf07, String udf08, String udf09, String udf10, String udf11, String udf12, BigDecimal udf57, BigDecimal udf58, BigDecimal udf59, BigDecimal udf60, BigDecimal udf61, BigDecimal udf62) {
       this.id = id;
       this.company = company;
       this.creator = creator;
       this.usrGroup = usrGroup;
       this.createDate = createDate;
       this.modifier = modifier;
       this.modiDate = modiDate;
       this.flag = flag;
       this.tv005 = tv005;
       this.tv006 = tv006;
       this.tv007 = tv007;
       this.tv008 = tv008;
       this.tv009 = tv009;
       this.tv010 = tv010;
       this.tv011 = tv011;
       this.tv012 = tv012;
       this.tv013 = tv013;
       this.udf01 = udf01;
       this.udf02 = udf02;
       this.udf03 = udf03;
       this.udf04 = udf04;
       this.udf05 = udf05;
       this.udf06 = udf06;
       this.udf51 = udf51;
       this.udf52 = udf52;
       this.udf53 = udf53;
       this.udf54 = udf54;
       this.udf55 = udf55;
       this.udf56 = udf56;
       this.udf07 = udf07;
       this.udf08 = udf08;
       this.udf09 = udf09;
       this.udf10 = udf10;
       this.udf11 = udf11;
       this.udf12 = udf12;
       this.udf57 = udf57;
       this.udf58 = udf58;
       this.udf59 = udf59;
       this.udf60 = udf60;
       this.udf61 = udf61;
       this.udf62 = udf62;
    }
   
    public CoptvId getId() {
        return this.id;
    }
    
    public void setId(CoptvId id) {
        this.id = id;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public String getUsrGroup() {
        return this.usrGroup;
    }
    
    public void setUsrGroup(String usrGroup) {
        this.usrGroup = usrGroup;
    }
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public String getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(String modiDate) {
        this.modiDate = modiDate;
    }
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }
    public BigDecimal getTv005() {
        return this.tv005;
    }
    
    public void setTv005(BigDecimal tv005) {
        this.tv005 = tv005;
    }
    public BigDecimal getTv006() {
        return this.tv006;
    }
    
    public void setTv006(BigDecimal tv006) {
        this.tv006 = tv006;
    }
    public String getTv007() {
        return this.tv007;
    }
    
    public void setTv007(String tv007) {
        this.tv007 = tv007;
    }
    public Character getTv008() {
        return this.tv008;
    }
    
    public void setTv008(Character tv008) {
        this.tv008 = tv008;
    }
    public String getTv009() {
        return this.tv009;
    }
    
    public void setTv009(String tv009) {
        this.tv009 = tv009;
    }
    public String getTv010() {
        return this.tv010;
    }
    
    public void setTv010(String tv010) {
        this.tv010 = tv010;
    }
    public BigDecimal getTv011() {
        return this.tv011;
    }
    
    public void setTv011(BigDecimal tv011) {
        this.tv011 = tv011;
    }
    public BigDecimal getTv012() {
        return this.tv012;
    }
    
    public void setTv012(BigDecimal tv012) {
        this.tv012 = tv012;
    }
    public BigDecimal getTv013() {
        return this.tv013;
    }
    
    public void setTv013(BigDecimal tv013) {
        this.tv013 = tv013;
    }
    public String getUdf01() {
        return this.udf01;
    }
    
    public void setUdf01(String udf01) {
        this.udf01 = udf01;
    }
    public String getUdf02() {
        return this.udf02;
    }
    
    public void setUdf02(String udf02) {
        this.udf02 = udf02;
    }
    public String getUdf03() {
        return this.udf03;
    }
    
    public void setUdf03(String udf03) {
        this.udf03 = udf03;
    }
    public String getUdf04() {
        return this.udf04;
    }
    
    public void setUdf04(String udf04) {
        this.udf04 = udf04;
    }
    public String getUdf05() {
        return this.udf05;
    }
    
    public void setUdf05(String udf05) {
        this.udf05 = udf05;
    }
    public String getUdf06() {
        return this.udf06;
    }
    
    public void setUdf06(String udf06) {
        this.udf06 = udf06;
    }
    public BigDecimal getUdf51() {
        return this.udf51;
    }
    
    public void setUdf51(BigDecimal udf51) {
        this.udf51 = udf51;
    }
    public BigDecimal getUdf52() {
        return this.udf52;
    }
    
    public void setUdf52(BigDecimal udf52) {
        this.udf52 = udf52;
    }
    public BigDecimal getUdf53() {
        return this.udf53;
    }
    
    public void setUdf53(BigDecimal udf53) {
        this.udf53 = udf53;
    }
    public BigDecimal getUdf54() {
        return this.udf54;
    }
    
    public void setUdf54(BigDecimal udf54) {
        this.udf54 = udf54;
    }
    public BigDecimal getUdf55() {
        return this.udf55;
    }
    
    public void setUdf55(BigDecimal udf55) {
        this.udf55 = udf55;
    }
    public BigDecimal getUdf56() {
        return this.udf56;
    }
    
    public void setUdf56(BigDecimal udf56) {
        this.udf56 = udf56;
    }
    public String getUdf07() {
        return this.udf07;
    }
    
    public void setUdf07(String udf07) {
        this.udf07 = udf07;
    }
    public String getUdf08() {
        return this.udf08;
    }
    
    public void setUdf08(String udf08) {
        this.udf08 = udf08;
    }
    public String getUdf09() {
        return this.udf09;
    }
    
    public void setUdf09(String udf09) {
        this.udf09 = udf09;
    }
    public String getUdf10() {
        return this.udf10;
    }
    
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }
    public String getUdf11() {
        return this.udf11;
    }
    
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }
    public String getUdf12() {
        return this.udf12;
    }
    
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }
    public BigDecimal getUdf57() {
        return this.udf57;
    }
    
    public void setUdf57(BigDecimal udf57) {
        this.udf57 = udf57;
    }
    public BigDecimal getUdf58() {
        return this.udf58;
    }
    
    public void setUdf58(BigDecimal udf58) {
        this.udf58 = udf58;
    }
    public BigDecimal getUdf59() {
        return this.udf59;
    }
    
    public void setUdf59(BigDecimal udf59) {
        this.udf59 = udf59;
    }
    public BigDecimal getUdf60() {
        return this.udf60;
    }
    
    public void setUdf60(BigDecimal udf60) {
        this.udf60 = udf60;
    }
    public BigDecimal getUdf61() {
        return this.udf61;
    }
    
    public void setUdf61(BigDecimal udf61) {
        this.udf61 = udf61;
    }
    public BigDecimal getUdf62() {
        return this.udf62;
    }
    
    public void setUdf62(BigDecimal udf62) {
        this.udf62 = udf62;
    }




}


