/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edwin.my.Cost;

import SqlInterface.QueryErp;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;

/**
 *
 * @author EDWIN
 */
public class EditCost extends javax.swing.JPanel {

    private String ph = "";
    private BigDecimal materialPriceA = BigDecimal.ZERO;
    private BigDecimal laborePriceA = BigDecimal.ZERO;
    private BigDecimal madePriceA = BigDecimal.ZERO;
    private BigDecimal cooperationPriceA = BigDecimal.ZERO;
    private BigDecimal sumPriceA = BigDecimal.ONE;
    private ArrayList aList = new ArrayList();

    /**
     * Creates new form EditCost
     */
    public EditCost(String ph) {
        initComponents();
        this.ph = ph;
        setINVMB();
    }

    private void setINVMB() {
//        try {
        GetINVMB gb = new GetINVMB(ph);
//            ArrayList alist = new ArrayList();
//            alist = gb.getInvmbDetail();

        MB001.setText(gb.getMB001());
        MB002.setText(gb.getMB002());
        MB003.setText(gb.getMB003());
        MB110.setText(gb.getMB110());
        MB004.setText(gb.getMB004());
        MB025.setText(gb.getMB025());
        materialPrice.setText(String.valueOf(gb.getMaterialPrice()));
        laborePrice.setText(String.valueOf(gb.getLaborePrice()));
        madePrice.setText(String.valueOf(gb.getMadePrice()));
        cooperationPrice.setText(String.valueOf(gb.getCooperationPrice()));
        sumPrice.setText(String.valueOf(gb.getSumPrice()));

        materialPriceA = gb.getMaterialPrice();
        laborePriceA = gb.getLaborePrice();
        madePriceA = gb.getMadePrice();
        cooperationPriceA = gb.getCooperationPrice();
        sumPriceA = gb.getSumPrice();





//        } catch (ClassNotFoundException ex) {
//            Exceptions.printStackTrace(ex);
//        } catch (SQLException ex) {
//            Exceptions.printStackTrace(ex);
//        }

    }

    public void saveToCost() throws ClassNotFoundException, SQLException {

        aList.removeAll(aList);
        aList.add(ph);
        aList.add(materialPrice.getText());
        aList.add(laborePrice.getText());
        aList.add(madePrice.getText());
        aList.add(cooperationPrice.getText());

        String sql = "{CALL procCostINVMBCupdate (?,?,?,?,?)}";
        QueryErp qr = Lookup.getDefault().lookup(QueryErp.class);
        if (qr instanceof QueryErp) {
            qr.rsErpProcList(sql, aList);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MB110 = new javax.swing.JTextField();
        MB003 = new javax.swing.JTextField();
        MB002 = new javax.swing.JTextField();
        MB001 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cooperationPrice = new javax.swing.JTextField();
        madePrice = new javax.swing.JTextField();
        laborePrice = new javax.swing.JTextField();
        materialPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sumPrice = new javax.swing.JTextField();
        MB025 = new javax.swing.JTextField();
        MB004 = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(603, 243));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.jLabel5.text")); // NOI18N

        MB110.setEditable(false);
        MB110.setText(org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.MB110.text")); // NOI18N
        MB110.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        MB003.setEditable(false);
        MB003.setText(org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.MB003.text")); // NOI18N
        MB003.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        MB002.setEditable(false);
        MB002.setText(org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.MB002.text")); // NOI18N
        MB002.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        MB001.setEditable(false);
        MB001.setText(org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.MB001.text")); // NOI18N
        MB001.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.jLabel8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.jLabel9.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.jLabel10.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.jLabel11.text")); // NOI18N

        cooperationPrice.setText(org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.cooperationPrice.text")); // NOI18N
        cooperationPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        madePrice.setText(org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.madePrice.text")); // NOI18N
        madePrice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        laborePrice.setText(org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.laborePrice.text")); // NOI18N
        laborePrice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        materialPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.jLabel6.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.jLabel12.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.jLabel7.text")); // NOI18N

        sumPrice.setEditable(false);
        sumPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        MB025.setEditable(false);
        MB025.setText(org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.MB025.text")); // NOI18N
        MB025.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        MB004.setEditable(false);
        MB004.setText(org.openide.util.NbBundle.getMessage(EditCost.class, "EditCost.MB004.text")); // NOI18N
        MB004.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MB001, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(MB002)
                    .addComponent(MB003)
                    .addComponent(MB110)
                    .addComponent(MB025, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MB004))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cooperationPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(materialPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(laborePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(madePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sumPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(MB001, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(MB002, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(laborePrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MB003, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(madePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MB110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cooperationPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(MB004, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(sumPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(MB025, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MB001;
    private javax.swing.JTextField MB002;
    private javax.swing.JTextField MB003;
    private javax.swing.JTextField MB004;
    private javax.swing.JTextField MB025;
    private javax.swing.JTextField MB110;
    private javax.swing.JTextField cooperationPrice;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField laborePrice;
    private javax.swing.JTextField madePrice;
    private javax.swing.JTextField materialPrice;
    private javax.swing.JTextField sumPrice;
    // End of variables declaration//GEN-END:variables
}
