package com.edwin.SFC;
// Generated Jun 13, 2013 1:39:36 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Cmsme generated by hbm2java
 */
public class Cmsme  implements java.io.Serializable {


     private String me001;
     private String company;
     private String creator;
     private String usrGroup;
     private String createDate;
     private String modifier;
     private String modiDate;
     private Short flag;
     private String me002;
     private String me003;
     private String me004;
     private Character me005;
     private Character me006;
     private String me007;
     private Character me008;
     private Character me009;
     private String me010;
     private String me011;
     private BigDecimal me012;
     private BigDecimal me013;
     private BigDecimal me014;
     private Character me015;
     private String udf01;
     private String udf02;
     private String udf03;
     private String udf04;
     private String udf05;
     private String udf06;
     private BigDecimal udf51;
     private BigDecimal udf52;
     private BigDecimal udf53;
     private BigDecimal udf54;
     private BigDecimal udf55;
     private BigDecimal udf56;
     private String udf07;
     private String udf08;
     private String udf09;
     private String udf10;
     private String udf11;
     private String udf12;
     private BigDecimal udf57;
     private BigDecimal udf58;
     private BigDecimal udf59;
     private BigDecimal udf60;
     private BigDecimal udf61;
     private BigDecimal udf62;

    public Cmsme() {
    }

	
    public Cmsme(String me001) {
        this.me001 = me001;
    }
    public Cmsme(String me001, String company, String creator, String usrGroup, String createDate, String modifier, String modiDate, Short flag, String me002, String me003, String me004, Character me005, Character me006, String me007, Character me008, Character me009, String me010, String me011, BigDecimal me012, BigDecimal me013, BigDecimal me014, Character me015, String udf01, String udf02, String udf03, String udf04, String udf05, String udf06, BigDecimal udf51, BigDecimal udf52, BigDecimal udf53, BigDecimal udf54, BigDecimal udf55, BigDecimal udf56, String udf07, String udf08, String udf09, String udf10, String udf11, String udf12, BigDecimal udf57, BigDecimal udf58, BigDecimal udf59, BigDecimal udf60, BigDecimal udf61, BigDecimal udf62) {
       this.me001 = me001;
       this.company = company;
       this.creator = creator;
       this.usrGroup = usrGroup;
       this.createDate = createDate;
       this.modifier = modifier;
       this.modiDate = modiDate;
       this.flag = flag;
       this.me002 = me002;
       this.me003 = me003;
       this.me004 = me004;
       this.me005 = me005;
       this.me006 = me006;
       this.me007 = me007;
       this.me008 = me008;
       this.me009 = me009;
       this.me010 = me010;
       this.me011 = me011;
       this.me012 = me012;
       this.me013 = me013;
       this.me014 = me014;
       this.me015 = me015;
       this.udf01 = udf01;
       this.udf02 = udf02;
       this.udf03 = udf03;
       this.udf04 = udf04;
       this.udf05 = udf05;
       this.udf06 = udf06;
       this.udf51 = udf51;
       this.udf52 = udf52;
       this.udf53 = udf53;
       this.udf54 = udf54;
       this.udf55 = udf55;
       this.udf56 = udf56;
       this.udf07 = udf07;
       this.udf08 = udf08;
       this.udf09 = udf09;
       this.udf10 = udf10;
       this.udf11 = udf11;
       this.udf12 = udf12;
       this.udf57 = udf57;
       this.udf58 = udf58;
       this.udf59 = udf59;
       this.udf60 = udf60;
       this.udf61 = udf61;
       this.udf62 = udf62;
    }
   
    public String getMe001() {
        return this.me001;
    }
    
    public void setMe001(String me001) {
        this.me001 = me001;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public String getUsrGroup() {
        return this.usrGroup;
    }
    
    public void setUsrGroup(String usrGroup) {
        this.usrGroup = usrGroup;
    }
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public String getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(String modiDate) {
        this.modiDate = modiDate;
    }
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }
    public String getMe002() {
        return this.me002;
    }
    
    public void setMe002(String me002) {
        this.me002 = me002;
    }
    public String getMe003() {
        return this.me003;
    }
    
    public void setMe003(String me003) {
        this.me003 = me003;
    }
    public String getMe004() {
        return this.me004;
    }
    
    public void setMe004(String me004) {
        this.me004 = me004;
    }
    public Character getMe005() {
        return this.me005;
    }
    
    public void setMe005(Character me005) {
        this.me005 = me005;
    }
    public Character getMe006() {
        return this.me006;
    }
    
    public void setMe006(Character me006) {
        this.me006 = me006;
    }
    public String getMe007() {
        return this.me007;
    }
    
    public void setMe007(String me007) {
        this.me007 = me007;
    }
    public Character getMe008() {
        return this.me008;
    }
    
    public void setMe008(Character me008) {
        this.me008 = me008;
    }
    public Character getMe009() {
        return this.me009;
    }
    
    public void setMe009(Character me009) {
        this.me009 = me009;
    }
    public String getMe010() {
        return this.me010;
    }
    
    public void setMe010(String me010) {
        this.me010 = me010;
    }
    public String getMe011() {
        return this.me011;
    }
    
    public void setMe011(String me011) {
        this.me011 = me011;
    }
    public BigDecimal getMe012() {
        return this.me012;
    }
    
    public void setMe012(BigDecimal me012) {
        this.me012 = me012;
    }
    public BigDecimal getMe013() {
        return this.me013;
    }
    
    public void setMe013(BigDecimal me013) {
        this.me013 = me013;
    }
    public BigDecimal getMe014() {
        return this.me014;
    }
    
    public void setMe014(BigDecimal me014) {
        this.me014 = me014;
    }
    public Character getMe015() {
        return this.me015;
    }
    
    public void setMe015(Character me015) {
        this.me015 = me015;
    }
    public String getUdf01() {
        return this.udf01;
    }
    
    public void setUdf01(String udf01) {
        this.udf01 = udf01;
    }
    public String getUdf02() {
        return this.udf02;
    }
    
    public void setUdf02(String udf02) {
        this.udf02 = udf02;
    }
    public String getUdf03() {
        return this.udf03;
    }
    
    public void setUdf03(String udf03) {
        this.udf03 = udf03;
    }
    public String getUdf04() {
        return this.udf04;
    }
    
    public void setUdf04(String udf04) {
        this.udf04 = udf04;
    }
    public String getUdf05() {
        return this.udf05;
    }
    
    public void setUdf05(String udf05) {
        this.udf05 = udf05;
    }
    public String getUdf06() {
        return this.udf06;
    }
    
    public void setUdf06(String udf06) {
        this.udf06 = udf06;
    }
    public BigDecimal getUdf51() {
        return this.udf51;
    }
    
    public void setUdf51(BigDecimal udf51) {
        this.udf51 = udf51;
    }
    public BigDecimal getUdf52() {
        return this.udf52;
    }
    
    public void setUdf52(BigDecimal udf52) {
        this.udf52 = udf52;
    }
    public BigDecimal getUdf53() {
        return this.udf53;
    }
    
    public void setUdf53(BigDecimal udf53) {
        this.udf53 = udf53;
    }
    public BigDecimal getUdf54() {
        return this.udf54;
    }
    
    public void setUdf54(BigDecimal udf54) {
        this.udf54 = udf54;
    }
    public BigDecimal getUdf55() {
        return this.udf55;
    }
    
    public void setUdf55(BigDecimal udf55) {
        this.udf55 = udf55;
    }
    public BigDecimal getUdf56() {
        return this.udf56;
    }
    
    public void setUdf56(BigDecimal udf56) {
        this.udf56 = udf56;
    }
    public String getUdf07() {
        return this.udf07;
    }
    
    public void setUdf07(String udf07) {
        this.udf07 = udf07;
    }
    public String getUdf08() {
        return this.udf08;
    }
    
    public void setUdf08(String udf08) {
        this.udf08 = udf08;
    }
    public String getUdf09() {
        return this.udf09;
    }
    
    public void setUdf09(String udf09) {
        this.udf09 = udf09;
    }
    public String getUdf10() {
        return this.udf10;
    }
    
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }
    public String getUdf11() {
        return this.udf11;
    }
    
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }
    public String getUdf12() {
        return this.udf12;
    }
    
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }
    public BigDecimal getUdf57() {
        return this.udf57;
    }
    
    public void setUdf57(BigDecimal udf57) {
        this.udf57 = udf57;
    }
    public BigDecimal getUdf58() {
        return this.udf58;
    }
    
    public void setUdf58(BigDecimal udf58) {
        this.udf58 = udf58;
    }
    public BigDecimal getUdf59() {
        return this.udf59;
    }
    
    public void setUdf59(BigDecimal udf59) {
        this.udf59 = udf59;
    }
    public BigDecimal getUdf60() {
        return this.udf60;
    }
    
    public void setUdf60(BigDecimal udf60) {
        this.udf60 = udf60;
    }
    public BigDecimal getUdf61() {
        return this.udf61;
    }
    
    public void setUdf61(BigDecimal udf61) {
        this.udf61 = udf61;
    }
    public BigDecimal getUdf62() {
        return this.udf62;
    }
    
    public void setUdf62(BigDecimal udf62) {
        this.udf62 = udf62;
    }




}


