package com.edwin.SFC;
// Generated Aug 9, 2013 10:54:42 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Cmsmq generated by hbm2java
 */
public class Cmsmq  implements java.io.Serializable {


     private String mq001;
     private String company;
     private String creator;
     private String usrGroup;
     private String createDate;
     private String modifier;
     private String modiDate;
     private Short flag;
     private String mq002;
     private String mq003;
     private Character mq004;
     private Boolean mq005;
     private Byte mq006;
     private Short mq007;
     private Character mq008;
     private String mq009;
     private Boolean mq010;
     private Character mq011;
     private Character mq012;
     private Character mq013;
     private Character mq014;
     private Character mq015;
     private Character mq016;
     private Character mq017;
     private Character mq018;
     private Character mq019;
     private Character mq020;
     private String mq021;
     private String mq022;
     private String mq023;
     private Character mq024;
     private String mq025;
     private Character mq026;
     private String mq027;
     private Character mq028;
     private Character mq029;
     private Character mq030;
     private Character mq031;
     private String mq032;
     private Character mq033;
     private String mq034;
     private Character mq035;
     private Character mq036;
     private BigDecimal mq037;
     private String mq038;
     private Character mq039;
     private Character mq040;
     private Character mq041;
     private Character mq042;
     private Character mq043;
     private Character mq044;
     private Character mq045;
     private Character mq046;
     private Character mq047;
     private String mq048;
     private Character mq049;
     private Character mq050;
     private Character mq051;
     private Byte mq052;
     private Byte mq053;
     private Character mq054;
     private String mq055;
     private String mq056;
     private BigDecimal mq057;
     private BigDecimal mq058;
     private BigDecimal mq059;
     private Character mq060;
     private Character mq061;
     private Character mq062;
     private String mq063;
     private Character mq064;
     private Character mq065;
     private Character mq066;
     private Character mq067;
     private Character mqd01;
     private Character mqd02;
     private Character mqd03;
     private Character mqd04;
     private Character mqd05;
     private Character mqd06;
     private String mqc01;
     private Character mqc02;
     private Character mqc03;
     private Character mqc04;
     private Character mqc05;
     private Character mq068;
     private String mq069;
     private Character mq070;
     private Character mq071;
     private Character mq072;
     private Character mq073;
     private Character mqi01;
     private Character mqi02;
     private String mq074;
     private String mq075;
     private String mq076;
     private String udf01;
     private String udf02;
     private String udf03;
     private String udf04;
     private String udf05;
     private String udf06;
     private BigDecimal udf51;
     private BigDecimal udf52;
     private BigDecimal udf53;
     private BigDecimal udf54;
     private BigDecimal udf55;
     private BigDecimal udf56;
     private String udf07;
     private String udf08;
     private String udf09;
     private String udf10;
     private String udf11;
     private String udf12;
     private BigDecimal udf57;
     private BigDecimal udf58;
     private BigDecimal udf59;
     private BigDecimal udf60;
     private BigDecimal udf61;
     private BigDecimal udf62;

    public Cmsmq() {
    }

	
    public Cmsmq(String mq001) {
        this.mq001 = mq001;
    }
    public Cmsmq(String mq001, String company, String creator, String usrGroup, String createDate, String modifier, String modiDate, Short flag, String mq002, String mq003, Character mq004, Boolean mq005, Byte mq006, Short mq007, Character mq008, String mq009, Boolean mq010, Character mq011, Character mq012, Character mq013, Character mq014, Character mq015, Character mq016, Character mq017, Character mq018, Character mq019, Character mq020, String mq021, String mq022, String mq023, Character mq024, String mq025, Character mq026, String mq027, Character mq028, Character mq029, Character mq030, Character mq031, String mq032, Character mq033, String mq034, Character mq035, Character mq036, BigDecimal mq037, String mq038, Character mq039, Character mq040, Character mq041, Character mq042, Character mq043, Character mq044, Character mq045, Character mq046, Character mq047, String mq048, Character mq049, Character mq050, Character mq051, Byte mq052, Byte mq053, Character mq054, String mq055, String mq056, BigDecimal mq057, BigDecimal mq058, BigDecimal mq059, Character mq060, Character mq061, Character mq062, String mq063, Character mq064, Character mq065, Character mq066, Character mq067, Character mqd01, Character mqd02, Character mqd03, Character mqd04, Character mqd05, Character mqd06, String mqc01, Character mqc02, Character mqc03, Character mqc04, Character mqc05, Character mq068, String mq069, Character mq070, Character mq071, Character mq072, Character mq073, Character mqi01, Character mqi02, String mq074, String mq075, String mq076, String udf01, String udf02, String udf03, String udf04, String udf05, String udf06, BigDecimal udf51, BigDecimal udf52, BigDecimal udf53, BigDecimal udf54, BigDecimal udf55, BigDecimal udf56, String udf07, String udf08, String udf09, String udf10, String udf11, String udf12, BigDecimal udf57, BigDecimal udf58, BigDecimal udf59, BigDecimal udf60, BigDecimal udf61, BigDecimal udf62) {
       this.mq001 = mq001;
       this.company = company;
       this.creator = creator;
       this.usrGroup = usrGroup;
       this.createDate = createDate;
       this.modifier = modifier;
       this.modiDate = modiDate;
       this.flag = flag;
       this.mq002 = mq002;
       this.mq003 = mq003;
       this.mq004 = mq004;
       this.mq005 = mq005;
       this.mq006 = mq006;
       this.mq007 = mq007;
       this.mq008 = mq008;
       this.mq009 = mq009;
       this.mq010 = mq010;
       this.mq011 = mq011;
       this.mq012 = mq012;
       this.mq013 = mq013;
       this.mq014 = mq014;
       this.mq015 = mq015;
       this.mq016 = mq016;
       this.mq017 = mq017;
       this.mq018 = mq018;
       this.mq019 = mq019;
       this.mq020 = mq020;
       this.mq021 = mq021;
       this.mq022 = mq022;
       this.mq023 = mq023;
       this.mq024 = mq024;
       this.mq025 = mq025;
       this.mq026 = mq026;
       this.mq027 = mq027;
       this.mq028 = mq028;
       this.mq029 = mq029;
       this.mq030 = mq030;
       this.mq031 = mq031;
       this.mq032 = mq032;
       this.mq033 = mq033;
       this.mq034 = mq034;
       this.mq035 = mq035;
       this.mq036 = mq036;
       this.mq037 = mq037;
       this.mq038 = mq038;
       this.mq039 = mq039;
       this.mq040 = mq040;
       this.mq041 = mq041;
       this.mq042 = mq042;
       this.mq043 = mq043;
       this.mq044 = mq044;
       this.mq045 = mq045;
       this.mq046 = mq046;
       this.mq047 = mq047;
       this.mq048 = mq048;
       this.mq049 = mq049;
       this.mq050 = mq050;
       this.mq051 = mq051;
       this.mq052 = mq052;
       this.mq053 = mq053;
       this.mq054 = mq054;
       this.mq055 = mq055;
       this.mq056 = mq056;
       this.mq057 = mq057;
       this.mq058 = mq058;
       this.mq059 = mq059;
       this.mq060 = mq060;
       this.mq061 = mq061;
       this.mq062 = mq062;
       this.mq063 = mq063;
       this.mq064 = mq064;
       this.mq065 = mq065;
       this.mq066 = mq066;
       this.mq067 = mq067;
       this.mqd01 = mqd01;
       this.mqd02 = mqd02;
       this.mqd03 = mqd03;
       this.mqd04 = mqd04;
       this.mqd05 = mqd05;
       this.mqd06 = mqd06;
       this.mqc01 = mqc01;
       this.mqc02 = mqc02;
       this.mqc03 = mqc03;
       this.mqc04 = mqc04;
       this.mqc05 = mqc05;
       this.mq068 = mq068;
       this.mq069 = mq069;
       this.mq070 = mq070;
       this.mq071 = mq071;
       this.mq072 = mq072;
       this.mq073 = mq073;
       this.mqi01 = mqi01;
       this.mqi02 = mqi02;
       this.mq074 = mq074;
       this.mq075 = mq075;
       this.mq076 = mq076;
       this.udf01 = udf01;
       this.udf02 = udf02;
       this.udf03 = udf03;
       this.udf04 = udf04;
       this.udf05 = udf05;
       this.udf06 = udf06;
       this.udf51 = udf51;
       this.udf52 = udf52;
       this.udf53 = udf53;
       this.udf54 = udf54;
       this.udf55 = udf55;
       this.udf56 = udf56;
       this.udf07 = udf07;
       this.udf08 = udf08;
       this.udf09 = udf09;
       this.udf10 = udf10;
       this.udf11 = udf11;
       this.udf12 = udf12;
       this.udf57 = udf57;
       this.udf58 = udf58;
       this.udf59 = udf59;
       this.udf60 = udf60;
       this.udf61 = udf61;
       this.udf62 = udf62;
    }
   
    public String getMq001() {
        return this.mq001;
    }
    
    public void setMq001(String mq001) {
        this.mq001 = mq001;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public String getUsrGroup() {
        return this.usrGroup;
    }
    
    public void setUsrGroup(String usrGroup) {
        this.usrGroup = usrGroup;
    }
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public String getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(String modiDate) {
        this.modiDate = modiDate;
    }
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }
    public String getMq002() {
        return this.mq002;
    }
    
    public void setMq002(String mq002) {
        this.mq002 = mq002;
    }
    public String getMq003() {
        return this.mq003;
    }
    
    public void setMq003(String mq003) {
        this.mq003 = mq003;
    }
    public Character getMq004() {
        return this.mq004;
    }
    
    public void setMq004(Character mq004) {
        this.mq004 = mq004;
    }
    public Boolean getMq005() {
        return this.mq005;
    }
    
    public void setMq005(Boolean mq005) {
        this.mq005 = mq005;
    }
    public Byte getMq006() {
        return this.mq006;
    }
    
    public void setMq006(Byte mq006) {
        this.mq006 = mq006;
    }
    public Short getMq007() {
        return this.mq007;
    }
    
    public void setMq007(Short mq007) {
        this.mq007 = mq007;
    }
    public Character getMq008() {
        return this.mq008;
    }
    
    public void setMq008(Character mq008) {
        this.mq008 = mq008;
    }
    public String getMq009() {
        return this.mq009;
    }
    
    public void setMq009(String mq009) {
        this.mq009 = mq009;
    }
    public Boolean getMq010() {
        return this.mq010;
    }
    
    public void setMq010(Boolean mq010) {
        this.mq010 = mq010;
    }
    public Character getMq011() {
        return this.mq011;
    }
    
    public void setMq011(Character mq011) {
        this.mq011 = mq011;
    }
    public Character getMq012() {
        return this.mq012;
    }
    
    public void setMq012(Character mq012) {
        this.mq012 = mq012;
    }
    public Character getMq013() {
        return this.mq013;
    }
    
    public void setMq013(Character mq013) {
        this.mq013 = mq013;
    }
    public Character getMq014() {
        return this.mq014;
    }
    
    public void setMq014(Character mq014) {
        this.mq014 = mq014;
    }
    public Character getMq015() {
        return this.mq015;
    }
    
    public void setMq015(Character mq015) {
        this.mq015 = mq015;
    }
    public Character getMq016() {
        return this.mq016;
    }
    
    public void setMq016(Character mq016) {
        this.mq016 = mq016;
    }
    public Character getMq017() {
        return this.mq017;
    }
    
    public void setMq017(Character mq017) {
        this.mq017 = mq017;
    }
    public Character getMq018() {
        return this.mq018;
    }
    
    public void setMq018(Character mq018) {
        this.mq018 = mq018;
    }
    public Character getMq019() {
        return this.mq019;
    }
    
    public void setMq019(Character mq019) {
        this.mq019 = mq019;
    }
    public Character getMq020() {
        return this.mq020;
    }
    
    public void setMq020(Character mq020) {
        this.mq020 = mq020;
    }
    public String getMq021() {
        return this.mq021;
    }
    
    public void setMq021(String mq021) {
        this.mq021 = mq021;
    }
    public String getMq022() {
        return this.mq022;
    }
    
    public void setMq022(String mq022) {
        this.mq022 = mq022;
    }
    public String getMq023() {
        return this.mq023;
    }
    
    public void setMq023(String mq023) {
        this.mq023 = mq023;
    }
    public Character getMq024() {
        return this.mq024;
    }
    
    public void setMq024(Character mq024) {
        this.mq024 = mq024;
    }
    public String getMq025() {
        return this.mq025;
    }
    
    public void setMq025(String mq025) {
        this.mq025 = mq025;
    }
    public Character getMq026() {
        return this.mq026;
    }
    
    public void setMq026(Character mq026) {
        this.mq026 = mq026;
    }
    public String getMq027() {
        return this.mq027;
    }
    
    public void setMq027(String mq027) {
        this.mq027 = mq027;
    }
    public Character getMq028() {
        return this.mq028;
    }
    
    public void setMq028(Character mq028) {
        this.mq028 = mq028;
    }
    public Character getMq029() {
        return this.mq029;
    }
    
    public void setMq029(Character mq029) {
        this.mq029 = mq029;
    }
    public Character getMq030() {
        return this.mq030;
    }
    
    public void setMq030(Character mq030) {
        this.mq030 = mq030;
    }
    public Character getMq031() {
        return this.mq031;
    }
    
    public void setMq031(Character mq031) {
        this.mq031 = mq031;
    }
    public String getMq032() {
        return this.mq032;
    }
    
    public void setMq032(String mq032) {
        this.mq032 = mq032;
    }
    public Character getMq033() {
        return this.mq033;
    }
    
    public void setMq033(Character mq033) {
        this.mq033 = mq033;
    }
    public String getMq034() {
        return this.mq034;
    }
    
    public void setMq034(String mq034) {
        this.mq034 = mq034;
    }
    public Character getMq035() {
        return this.mq035;
    }
    
    public void setMq035(Character mq035) {
        this.mq035 = mq035;
    }
    public Character getMq036() {
        return this.mq036;
    }
    
    public void setMq036(Character mq036) {
        this.mq036 = mq036;
    }
    public BigDecimal getMq037() {
        return this.mq037;
    }
    
    public void setMq037(BigDecimal mq037) {
        this.mq037 = mq037;
    }
    public String getMq038() {
        return this.mq038;
    }
    
    public void setMq038(String mq038) {
        this.mq038 = mq038;
    }
    public Character getMq039() {
        return this.mq039;
    }
    
    public void setMq039(Character mq039) {
        this.mq039 = mq039;
    }
    public Character getMq040() {
        return this.mq040;
    }
    
    public void setMq040(Character mq040) {
        this.mq040 = mq040;
    }
    public Character getMq041() {
        return this.mq041;
    }
    
    public void setMq041(Character mq041) {
        this.mq041 = mq041;
    }
    public Character getMq042() {
        return this.mq042;
    }
    
    public void setMq042(Character mq042) {
        this.mq042 = mq042;
    }
    public Character getMq043() {
        return this.mq043;
    }
    
    public void setMq043(Character mq043) {
        this.mq043 = mq043;
    }
    public Character getMq044() {
        return this.mq044;
    }
    
    public void setMq044(Character mq044) {
        this.mq044 = mq044;
    }
    public Character getMq045() {
        return this.mq045;
    }
    
    public void setMq045(Character mq045) {
        this.mq045 = mq045;
    }
    public Character getMq046() {
        return this.mq046;
    }
    
    public void setMq046(Character mq046) {
        this.mq046 = mq046;
    }
    public Character getMq047() {
        return this.mq047;
    }
    
    public void setMq047(Character mq047) {
        this.mq047 = mq047;
    }
    public String getMq048() {
        return this.mq048;
    }
    
    public void setMq048(String mq048) {
        this.mq048 = mq048;
    }
    public Character getMq049() {
        return this.mq049;
    }
    
    public void setMq049(Character mq049) {
        this.mq049 = mq049;
    }
    public Character getMq050() {
        return this.mq050;
    }
    
    public void setMq050(Character mq050) {
        this.mq050 = mq050;
    }
    public Character getMq051() {
        return this.mq051;
    }
    
    public void setMq051(Character mq051) {
        this.mq051 = mq051;
    }
    public Byte getMq052() {
        return this.mq052;
    }
    
    public void setMq052(Byte mq052) {
        this.mq052 = mq052;
    }
    public Byte getMq053() {
        return this.mq053;
    }
    
    public void setMq053(Byte mq053) {
        this.mq053 = mq053;
    }
    public Character getMq054() {
        return this.mq054;
    }
    
    public void setMq054(Character mq054) {
        this.mq054 = mq054;
    }
    public String getMq055() {
        return this.mq055;
    }
    
    public void setMq055(String mq055) {
        this.mq055 = mq055;
    }
    public String getMq056() {
        return this.mq056;
    }
    
    public void setMq056(String mq056) {
        this.mq056 = mq056;
    }
    public BigDecimal getMq057() {
        return this.mq057;
    }
    
    public void setMq057(BigDecimal mq057) {
        this.mq057 = mq057;
    }
    public BigDecimal getMq058() {
        return this.mq058;
    }
    
    public void setMq058(BigDecimal mq058) {
        this.mq058 = mq058;
    }
    public BigDecimal getMq059() {
        return this.mq059;
    }
    
    public void setMq059(BigDecimal mq059) {
        this.mq059 = mq059;
    }
    public Character getMq060() {
        return this.mq060;
    }
    
    public void setMq060(Character mq060) {
        this.mq060 = mq060;
    }
    public Character getMq061() {
        return this.mq061;
    }
    
    public void setMq061(Character mq061) {
        this.mq061 = mq061;
    }
    public Character getMq062() {
        return this.mq062;
    }
    
    public void setMq062(Character mq062) {
        this.mq062 = mq062;
    }
    public String getMq063() {
        return this.mq063;
    }
    
    public void setMq063(String mq063) {
        this.mq063 = mq063;
    }
    public Character getMq064() {
        return this.mq064;
    }
    
    public void setMq064(Character mq064) {
        this.mq064 = mq064;
    }
    public Character getMq065() {
        return this.mq065;
    }
    
    public void setMq065(Character mq065) {
        this.mq065 = mq065;
    }
    public Character getMq066() {
        return this.mq066;
    }
    
    public void setMq066(Character mq066) {
        this.mq066 = mq066;
    }
    public Character getMq067() {
        return this.mq067;
    }
    
    public void setMq067(Character mq067) {
        this.mq067 = mq067;
    }
    public Character getMqd01() {
        return this.mqd01;
    }
    
    public void setMqd01(Character mqd01) {
        this.mqd01 = mqd01;
    }
    public Character getMqd02() {
        return this.mqd02;
    }
    
    public void setMqd02(Character mqd02) {
        this.mqd02 = mqd02;
    }
    public Character getMqd03() {
        return this.mqd03;
    }
    
    public void setMqd03(Character mqd03) {
        this.mqd03 = mqd03;
    }
    public Character getMqd04() {
        return this.mqd04;
    }
    
    public void setMqd04(Character mqd04) {
        this.mqd04 = mqd04;
    }
    public Character getMqd05() {
        return this.mqd05;
    }
    
    public void setMqd05(Character mqd05) {
        this.mqd05 = mqd05;
    }
    public Character getMqd06() {
        return this.mqd06;
    }
    
    public void setMqd06(Character mqd06) {
        this.mqd06 = mqd06;
    }
    public String getMqc01() {
        return this.mqc01;
    }
    
    public void setMqc01(String mqc01) {
        this.mqc01 = mqc01;
    }
    public Character getMqc02() {
        return this.mqc02;
    }
    
    public void setMqc02(Character mqc02) {
        this.mqc02 = mqc02;
    }
    public Character getMqc03() {
        return this.mqc03;
    }
    
    public void setMqc03(Character mqc03) {
        this.mqc03 = mqc03;
    }
    public Character getMqc04() {
        return this.mqc04;
    }
    
    public void setMqc04(Character mqc04) {
        this.mqc04 = mqc04;
    }
    public Character getMqc05() {
        return this.mqc05;
    }
    
    public void setMqc05(Character mqc05) {
        this.mqc05 = mqc05;
    }
    public Character getMq068() {
        return this.mq068;
    }
    
    public void setMq068(Character mq068) {
        this.mq068 = mq068;
    }
    public String getMq069() {
        return this.mq069;
    }
    
    public void setMq069(String mq069) {
        this.mq069 = mq069;
    }
    public Character getMq070() {
        return this.mq070;
    }
    
    public void setMq070(Character mq070) {
        this.mq070 = mq070;
    }
    public Character getMq071() {
        return this.mq071;
    }
    
    public void setMq071(Character mq071) {
        this.mq071 = mq071;
    }
    public Character getMq072() {
        return this.mq072;
    }
    
    public void setMq072(Character mq072) {
        this.mq072 = mq072;
    }
    public Character getMq073() {
        return this.mq073;
    }
    
    public void setMq073(Character mq073) {
        this.mq073 = mq073;
    }
    public Character getMqi01() {
        return this.mqi01;
    }
    
    public void setMqi01(Character mqi01) {
        this.mqi01 = mqi01;
    }
    public Character getMqi02() {
        return this.mqi02;
    }
    
    public void setMqi02(Character mqi02) {
        this.mqi02 = mqi02;
    }
    public String getMq074() {
        return this.mq074;
    }
    
    public void setMq074(String mq074) {
        this.mq074 = mq074;
    }
    public String getMq075() {
        return this.mq075;
    }
    
    public void setMq075(String mq075) {
        this.mq075 = mq075;
    }
    public String getMq076() {
        return this.mq076;
    }
    
    public void setMq076(String mq076) {
        this.mq076 = mq076;
    }
    public String getUdf01() {
        return this.udf01;
    }
    
    public void setUdf01(String udf01) {
        this.udf01 = udf01;
    }
    public String getUdf02() {
        return this.udf02;
    }
    
    public void setUdf02(String udf02) {
        this.udf02 = udf02;
    }
    public String getUdf03() {
        return this.udf03;
    }
    
    public void setUdf03(String udf03) {
        this.udf03 = udf03;
    }
    public String getUdf04() {
        return this.udf04;
    }
    
    public void setUdf04(String udf04) {
        this.udf04 = udf04;
    }
    public String getUdf05() {
        return this.udf05;
    }
    
    public void setUdf05(String udf05) {
        this.udf05 = udf05;
    }
    public String getUdf06() {
        return this.udf06;
    }
    
    public void setUdf06(String udf06) {
        this.udf06 = udf06;
    }
    public BigDecimal getUdf51() {
        return this.udf51;
    }
    
    public void setUdf51(BigDecimal udf51) {
        this.udf51 = udf51;
    }
    public BigDecimal getUdf52() {
        return this.udf52;
    }
    
    public void setUdf52(BigDecimal udf52) {
        this.udf52 = udf52;
    }
    public BigDecimal getUdf53() {
        return this.udf53;
    }
    
    public void setUdf53(BigDecimal udf53) {
        this.udf53 = udf53;
    }
    public BigDecimal getUdf54() {
        return this.udf54;
    }
    
    public void setUdf54(BigDecimal udf54) {
        this.udf54 = udf54;
    }
    public BigDecimal getUdf55() {
        return this.udf55;
    }
    
    public void setUdf55(BigDecimal udf55) {
        this.udf55 = udf55;
    }
    public BigDecimal getUdf56() {
        return this.udf56;
    }
    
    public void setUdf56(BigDecimal udf56) {
        this.udf56 = udf56;
    }
    public String getUdf07() {
        return this.udf07;
    }
    
    public void setUdf07(String udf07) {
        this.udf07 = udf07;
    }
    public String getUdf08() {
        return this.udf08;
    }
    
    public void setUdf08(String udf08) {
        this.udf08 = udf08;
    }
    public String getUdf09() {
        return this.udf09;
    }
    
    public void setUdf09(String udf09) {
        this.udf09 = udf09;
    }
    public String getUdf10() {
        return this.udf10;
    }
    
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }
    public String getUdf11() {
        return this.udf11;
    }
    
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }
    public String getUdf12() {
        return this.udf12;
    }
    
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }
    public BigDecimal getUdf57() {
        return this.udf57;
    }
    
    public void setUdf57(BigDecimal udf57) {
        this.udf57 = udf57;
    }
    public BigDecimal getUdf58() {
        return this.udf58;
    }
    
    public void setUdf58(BigDecimal udf58) {
        this.udf58 = udf58;
    }
    public BigDecimal getUdf59() {
        return this.udf59;
    }
    
    public void setUdf59(BigDecimal udf59) {
        this.udf59 = udf59;
    }
    public BigDecimal getUdf60() {
        return this.udf60;
    }
    
    public void setUdf60(BigDecimal udf60) {
        this.udf60 = udf60;
    }
    public BigDecimal getUdf61() {
        return this.udf61;
    }
    
    public void setUdf61(BigDecimal udf61) {
        this.udf61 = udf61;
    }
    public BigDecimal getUdf62() {
        return this.udf62;
    }
    
    public void setUdf62(BigDecimal udf62) {
        this.udf62 = udf62;
    }




}


