package com.edwin.SFC;
// Generated Oct 26, 2013 9:03:44 AM by Hibernate Tools 3.6.0



/**
 * CopmfId generated by hbm2java
 */
public class CopmfId  implements java.io.Serializable {


     private String mf001;
     private String mf002;
     private String mf200;

    public CopmfId() {
    }

    public CopmfId(String mf001, String mf002, String mf200) {
       this.mf001 = mf001;
       this.mf002 = mf002;
       this.mf200 = mf200;
    }
   
    public String getMf001() {
        return this.mf001;
    }
    
    public void setMf001(String mf001) {
        this.mf001 = mf001;
    }
    public String getMf002() {
        return this.mf002;
    }
    
    public void setMf002(String mf002) {
        this.mf002 = mf002;
    }
    public String getMf200() {
        return this.mf200;
    }
    
    public void setMf200(String mf200) {
        this.mf200 = mf200;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CopmfId) ) return false;
		 CopmfId castOther = ( CopmfId ) other; 
         
		 return ( (this.getMf001()==castOther.getMf001()) || ( this.getMf001()!=null && castOther.getMf001()!=null && this.getMf001().equals(castOther.getMf001()) ) )
 && ( (this.getMf002()==castOther.getMf002()) || ( this.getMf002()!=null && castOther.getMf002()!=null && this.getMf002().equals(castOther.getMf002()) ) )
 && ( (this.getMf200()==castOther.getMf200()) || ( this.getMf200()!=null && castOther.getMf200()!=null && this.getMf200().equals(castOther.getMf200()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMf001() == null ? 0 : this.getMf001().hashCode() );
         result = 37 * result + ( getMf002() == null ? 0 : this.getMf002().hashCode() );
         result = 37 * result + ( getMf200() == null ? 0 : this.getMf200().hashCode() );
         return result;
   }   


}


