package com.edwin.SFC;
// Generated Jun 13, 2013 1:39:36 PM by Hibernate Tools 3.6.0



/**
 * SfctaId generated by hbm2java
 */
public class SfctaId  implements java.io.Serializable {


     private String ta001;
     private String ta002;
     private String ta003;
     private String ta006;

    public SfctaId() {
    }

    public SfctaId(String ta001, String ta002, String ta003, String ta006) {
       this.ta001 = ta001;
       this.ta002 = ta002;
       this.ta003 = ta003;
       this.ta006 = ta006;
    }
   
    public String getTa001() {
        return this.ta001;
    }
    
    public void setTa001(String ta001) {
        this.ta001 = ta001;
    }
    public String getTa002() {
        return this.ta002;
    }
    
    public void setTa002(String ta002) {
        this.ta002 = ta002;
    }
    public String getTa003() {
        return this.ta003;
    }
    
    public void setTa003(String ta003) {
        this.ta003 = ta003;
    }
    public String getTa006() {
        return this.ta006;
    }
    
    public void setTa006(String ta006) {
        this.ta006 = ta006;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SfctaId) ) return false;
		 SfctaId castOther = ( SfctaId ) other; 
         
		 return ( (this.getTa001()==castOther.getTa001()) || ( this.getTa001()!=null && castOther.getTa001()!=null && this.getTa001().equals(castOther.getTa001()) ) )
 && ( (this.getTa002()==castOther.getTa002()) || ( this.getTa002()!=null && castOther.getTa002()!=null && this.getTa002().equals(castOther.getTa002()) ) )
 && ( (this.getTa003()==castOther.getTa003()) || ( this.getTa003()!=null && castOther.getTa003()!=null && this.getTa003().equals(castOther.getTa003()) ) )
 && ( (this.getTa006()==castOther.getTa006()) || ( this.getTa006()!=null && castOther.getTa006()!=null && this.getTa006().equals(castOther.getTa006()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTa001() == null ? 0 : this.getTa001().hashCode() );
         result = 37 * result + ( getTa002() == null ? 0 : this.getTa002().hashCode() );
         result = 37 * result + ( getTa003() == null ? 0 : this.getTa003().hashCode() );
         result = 37 * result + ( getTa006() == null ? 0 : this.getTa006().hashCode() );
         return result;
   }   


}


