package com.edwin.SFC;
// Generated Jun 13, 2013 1:39:36 PM by Hibernate Tools 3.6.0



/**
 * SfctbId generated by hbm2java
 */
public class SfctbId  implements java.io.Serializable {


     private String tb001;
     private String tb002;

    public SfctbId() {
    }

    public SfctbId(String tb001, String tb002) {
       this.tb001 = tb001;
       this.tb002 = tb002;
    }
   
    public String getTb001() {
        return this.tb001;
    }
    
    public void setTb001(String tb001) {
        this.tb001 = tb001;
    }
    public String getTb002() {
        return this.tb002;
    }
    
    public void setTb002(String tb002) {
        this.tb002 = tb002;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SfctbId) ) return false;
		 SfctbId castOther = ( SfctbId ) other; 
         
		 return ( (this.getTb001()==castOther.getTb001()) || ( this.getTb001()!=null && castOther.getTb001()!=null && this.getTb001().equals(castOther.getTb001()) ) )
 && ( (this.getTb002()==castOther.getTb002()) || ( this.getTb002()!=null && castOther.getTb002()!=null && this.getTb002().equals(castOther.getTb002()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTb001() == null ? 0 : this.getTb001().hashCode() );
         result = 37 * result + ( getTb002() == null ? 0 : this.getTb002().hashCode() );
         return result;
   }   


}


