package com.edwin.SFC;
// Generated Jun 13, 2013 1:39:36 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Sfctb generated by hbm2java
 */
public class Sfctb  implements java.io.Serializable {


     private SfctbId id;
     private String company;
     private String creator;
     private String usrGroup;
     private String createDate;
     private String modifier;
     private String modiDate;
     private Short flag;
     private String tb003;
     private Character tb004;
     private String tb005;
     private String tb006;
     private Character tb007;
     private String tb008;
     private String tb009;
     private String tb010;
     private Boolean tb011;
     private Character tb012;
     private Character tb013;
     private String tb014;
     private String tb015;
     private String tb016;
     private Character tb017;
     private Boolean tb018;
     private Character tb019;
     private BigDecimal tb020;
     private String tb021;
     private BigDecimal tb022;
     private String tb023;
     private String tb024;
     private Character tb025;
     private String tb026;
     private String tb027;
     private BigDecimal tb028;
     private BigDecimal tb029;
     private BigDecimal tb030;
     private String tb031;
     private String udf01;
     private String udf02;
     private String udf03;
     private String udf04;
     private String udf05;
     private String udf06;
     private BigDecimal udf51;
     private BigDecimal udf52;
     private BigDecimal udf53;
     private BigDecimal udf54;
     private BigDecimal udf55;
     private BigDecimal udf56;
     private String udf07;
     private String udf08;
     private String udf09;
     private String udf10;
     private String udf11;
     private String udf12;
     private BigDecimal udf57;
     private BigDecimal udf58;
     private BigDecimal udf59;
     private BigDecimal udf60;
     private BigDecimal udf61;
     private BigDecimal udf62;

    public Sfctb() {
    }

	
    public Sfctb(SfctbId id) {
        this.id = id;
    }
    public Sfctb(SfctbId id, String company, String creator, String usrGroup, String createDate, String modifier, String modiDate, Short flag, String tb003, Character tb004, String tb005, String tb006, Character tb007, String tb008, String tb009, String tb010, Boolean tb011, Character tb012, Character tb013, String tb014, String tb015, String tb016, Character tb017, Boolean tb018, Character tb019, BigDecimal tb020, String tb021, BigDecimal tb022, String tb023, String tb024, Character tb025, String tb026, String tb027, BigDecimal tb028, BigDecimal tb029, BigDecimal tb030, String tb031, String udf01, String udf02, String udf03, String udf04, String udf05, String udf06, BigDecimal udf51, BigDecimal udf52, BigDecimal udf53, BigDecimal udf54, BigDecimal udf55, BigDecimal udf56, String udf07, String udf08, String udf09, String udf10, String udf11, String udf12, BigDecimal udf57, BigDecimal udf58, BigDecimal udf59, BigDecimal udf60, BigDecimal udf61, BigDecimal udf62) {
       this.id = id;
       this.company = company;
       this.creator = creator;
       this.usrGroup = usrGroup;
       this.createDate = createDate;
       this.modifier = modifier;
       this.modiDate = modiDate;
       this.flag = flag;
       this.tb003 = tb003;
       this.tb004 = tb004;
       this.tb005 = tb005;
       this.tb006 = tb006;
       this.tb007 = tb007;
       this.tb008 = tb008;
       this.tb009 = tb009;
       this.tb010 = tb010;
       this.tb011 = tb011;
       this.tb012 = tb012;
       this.tb013 = tb013;
       this.tb014 = tb014;
       this.tb015 = tb015;
       this.tb016 = tb016;
       this.tb017 = tb017;
       this.tb018 = tb018;
       this.tb019 = tb019;
       this.tb020 = tb020;
       this.tb021 = tb021;
       this.tb022 = tb022;
       this.tb023 = tb023;
       this.tb024 = tb024;
       this.tb025 = tb025;
       this.tb026 = tb026;
       this.tb027 = tb027;
       this.tb028 = tb028;
       this.tb029 = tb029;
       this.tb030 = tb030;
       this.tb031 = tb031;
       this.udf01 = udf01;
       this.udf02 = udf02;
       this.udf03 = udf03;
       this.udf04 = udf04;
       this.udf05 = udf05;
       this.udf06 = udf06;
       this.udf51 = udf51;
       this.udf52 = udf52;
       this.udf53 = udf53;
       this.udf54 = udf54;
       this.udf55 = udf55;
       this.udf56 = udf56;
       this.udf07 = udf07;
       this.udf08 = udf08;
       this.udf09 = udf09;
       this.udf10 = udf10;
       this.udf11 = udf11;
       this.udf12 = udf12;
       this.udf57 = udf57;
       this.udf58 = udf58;
       this.udf59 = udf59;
       this.udf60 = udf60;
       this.udf61 = udf61;
       this.udf62 = udf62;
    }
   
    public SfctbId getId() {
        return this.id;
    }
    
    public void setId(SfctbId id) {
        this.id = id;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public String getUsrGroup() {
        return this.usrGroup;
    }
    
    public void setUsrGroup(String usrGroup) {
        this.usrGroup = usrGroup;
    }
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public String getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(String modiDate) {
        this.modiDate = modiDate;
    }
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }
    public String getTb003() {
        return this.tb003;
    }
    
    public void setTb003(String tb003) {
        this.tb003 = tb003;
    }
    public Character getTb004() {
        return this.tb004;
    }
    
    public void setTb004(Character tb004) {
        this.tb004 = tb004;
    }
    public String getTb005() {
        return this.tb005;
    }
    
    public void setTb005(String tb005) {
        this.tb005 = tb005;
    }
    public String getTb006() {
        return this.tb006;
    }
    
    public void setTb006(String tb006) {
        this.tb006 = tb006;
    }
    public Character getTb007() {
        return this.tb007;
    }
    
    public void setTb007(Character tb007) {
        this.tb007 = tb007;
    }
    public String getTb008() {
        return this.tb008;
    }
    
    public void setTb008(String tb008) {
        this.tb008 = tb008;
    }
    public String getTb009() {
        return this.tb009;
    }
    
    public void setTb009(String tb009) {
        this.tb009 = tb009;
    }
    public String getTb010() {
        return this.tb010;
    }
    
    public void setTb010(String tb010) {
        this.tb010 = tb010;
    }
    public Boolean getTb011() {
        return this.tb011;
    }
    
    public void setTb011(Boolean tb011) {
        this.tb011 = tb011;
    }
    public Character getTb012() {
        return this.tb012;
    }
    
    public void setTb012(Character tb012) {
        this.tb012 = tb012;
    }
    public Character getTb013() {
        return this.tb013;
    }
    
    public void setTb013(Character tb013) {
        this.tb013 = tb013;
    }
    public String getTb014() {
        return this.tb014;
    }
    
    public void setTb014(String tb014) {
        this.tb014 = tb014;
    }
    public String getTb015() {
        return this.tb015;
    }
    
    public void setTb015(String tb015) {
        this.tb015 = tb015;
    }
    public String getTb016() {
        return this.tb016;
    }
    
    public void setTb016(String tb016) {
        this.tb016 = tb016;
    }
    public Character getTb017() {
        return this.tb017;
    }
    
    public void setTb017(Character tb017) {
        this.tb017 = tb017;
    }
    public Boolean getTb018() {
        return this.tb018;
    }
    
    public void setTb018(Boolean tb018) {
        this.tb018 = tb018;
    }
    public Character getTb019() {
        return this.tb019;
    }
    
    public void setTb019(Character tb019) {
        this.tb019 = tb019;
    }
    public BigDecimal getTb020() {
        return this.tb020;
    }
    
    public void setTb020(BigDecimal tb020) {
        this.tb020 = tb020;
    }
    public String getTb021() {
        return this.tb021;
    }
    
    public void setTb021(String tb021) {
        this.tb021 = tb021;
    }
    public BigDecimal getTb022() {
        return this.tb022;
    }
    
    public void setTb022(BigDecimal tb022) {
        this.tb022 = tb022;
    }
    public String getTb023() {
        return this.tb023;
    }
    
    public void setTb023(String tb023) {
        this.tb023 = tb023;
    }
    public String getTb024() {
        return this.tb024;
    }
    
    public void setTb024(String tb024) {
        this.tb024 = tb024;
    }
    public Character getTb025() {
        return this.tb025;
    }
    
    public void setTb025(Character tb025) {
        this.tb025 = tb025;
    }
    public String getTb026() {
        return this.tb026;
    }
    
    public void setTb026(String tb026) {
        this.tb026 = tb026;
    }
    public String getTb027() {
        return this.tb027;
    }
    
    public void setTb027(String tb027) {
        this.tb027 = tb027;
    }
    public BigDecimal getTb028() {
        return this.tb028;
    }
    
    public void setTb028(BigDecimal tb028) {
        this.tb028 = tb028;
    }
    public BigDecimal getTb029() {
        return this.tb029;
    }
    
    public void setTb029(BigDecimal tb029) {
        this.tb029 = tb029;
    }
    public BigDecimal getTb030() {
        return this.tb030;
    }
    
    public void setTb030(BigDecimal tb030) {
        this.tb030 = tb030;
    }
    public String getTb031() {
        return this.tb031;
    }
    
    public void setTb031(String tb031) {
        this.tb031 = tb031;
    }
    public String getUdf01() {
        return this.udf01;
    }
    
    public void setUdf01(String udf01) {
        this.udf01 = udf01;
    }
    public String getUdf02() {
        return this.udf02;
    }
    
    public void setUdf02(String udf02) {
        this.udf02 = udf02;
    }
    public String getUdf03() {
        return this.udf03;
    }
    
    public void setUdf03(String udf03) {
        this.udf03 = udf03;
    }
    public String getUdf04() {
        return this.udf04;
    }
    
    public void setUdf04(String udf04) {
        this.udf04 = udf04;
    }
    public String getUdf05() {
        return this.udf05;
    }
    
    public void setUdf05(String udf05) {
        this.udf05 = udf05;
    }
    public String getUdf06() {
        return this.udf06;
    }
    
    public void setUdf06(String udf06) {
        this.udf06 = udf06;
    }
    public BigDecimal getUdf51() {
        return this.udf51;
    }
    
    public void setUdf51(BigDecimal udf51) {
        this.udf51 = udf51;
    }
    public BigDecimal getUdf52() {
        return this.udf52;
    }
    
    public void setUdf52(BigDecimal udf52) {
        this.udf52 = udf52;
    }
    public BigDecimal getUdf53() {
        return this.udf53;
    }
    
    public void setUdf53(BigDecimal udf53) {
        this.udf53 = udf53;
    }
    public BigDecimal getUdf54() {
        return this.udf54;
    }
    
    public void setUdf54(BigDecimal udf54) {
        this.udf54 = udf54;
    }
    public BigDecimal getUdf55() {
        return this.udf55;
    }
    
    public void setUdf55(BigDecimal udf55) {
        this.udf55 = udf55;
    }
    public BigDecimal getUdf56() {
        return this.udf56;
    }
    
    public void setUdf56(BigDecimal udf56) {
        this.udf56 = udf56;
    }
    public String getUdf07() {
        return this.udf07;
    }
    
    public void setUdf07(String udf07) {
        this.udf07 = udf07;
    }
    public String getUdf08() {
        return this.udf08;
    }
    
    public void setUdf08(String udf08) {
        this.udf08 = udf08;
    }
    public String getUdf09() {
        return this.udf09;
    }
    
    public void setUdf09(String udf09) {
        this.udf09 = udf09;
    }
    public String getUdf10() {
        return this.udf10;
    }
    
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }
    public String getUdf11() {
        return this.udf11;
    }
    
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }
    public String getUdf12() {
        return this.udf12;
    }
    
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }
    public BigDecimal getUdf57() {
        return this.udf57;
    }
    
    public void setUdf57(BigDecimal udf57) {
        this.udf57 = udf57;
    }
    public BigDecimal getUdf58() {
        return this.udf58;
    }
    
    public void setUdf58(BigDecimal udf58) {
        this.udf58 = udf58;
    }
    public BigDecimal getUdf59() {
        return this.udf59;
    }
    
    public void setUdf59(BigDecimal udf59) {
        this.udf59 = udf59;
    }
    public BigDecimal getUdf60() {
        return this.udf60;
    }
    
    public void setUdf60(BigDecimal udf60) {
        this.udf60 = udf60;
    }
    public BigDecimal getUdf61() {
        return this.udf61;
    }
    
    public void setUdf61(BigDecimal udf61) {
        this.udf61 = udf61;
    }
    public BigDecimal getUdf62() {
        return this.udf62;
    }
    
    public void setUdf62(BigDecimal udf62) {
        this.udf62 = udf62;
    }




}


