package com.edwin.bomtable;
// Generated Sep 9, 2013 11:12:54 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Bommp generated by hbm2java
 */
public class Bommp  implements java.io.Serializable {


     private BommpId id;
     private String company;
     private String creator;
     private String usrGroup;
     private String createDate;
     private String modifier;
     private String modiDate;
     private Short flag;
     private BigDecimal mp005;
     private BigDecimal mp006;
     private String mp007;
     private String mp008;
     private String mp009;
     private Character mp010;
     private String mp011;
     private String mp012;
     private BigDecimal mp013;
     private BigDecimal mp014;
     private BigDecimal mp015;
     private String udf01;
     private String udf02;
     private String udf03;
     private String udf04;
     private String udf05;
     private String udf06;
     private BigDecimal udf51;
     private BigDecimal udf52;
     private BigDecimal udf53;
     private BigDecimal udf54;
     private BigDecimal udf55;
     private BigDecimal udf56;
     private String udf07;
     private String udf08;
     private String udf09;
     private String udf10;
     private String udf11;
     private String udf12;
     private BigDecimal udf57;
     private BigDecimal udf58;
     private BigDecimal udf59;
     private BigDecimal udf60;
     private BigDecimal udf61;
     private BigDecimal udf62;

    public Bommp() {
    }

	
    public Bommp(BommpId id) {
        this.id = id;
    }
    public Bommp(BommpId id, String company, String creator, String usrGroup, String createDate, String modifier, String modiDate, Short flag, BigDecimal mp005, BigDecimal mp006, String mp007, String mp008, String mp009, Character mp010, String mp011, String mp012, BigDecimal mp013, BigDecimal mp014, BigDecimal mp015, String udf01, String udf02, String udf03, String udf04, String udf05, String udf06, BigDecimal udf51, BigDecimal udf52, BigDecimal udf53, BigDecimal udf54, BigDecimal udf55, BigDecimal udf56, String udf07, String udf08, String udf09, String udf10, String udf11, String udf12, BigDecimal udf57, BigDecimal udf58, BigDecimal udf59, BigDecimal udf60, BigDecimal udf61, BigDecimal udf62) {
       this.id = id;
       this.company = company;
       this.creator = creator;
       this.usrGroup = usrGroup;
       this.createDate = createDate;
       this.modifier = modifier;
       this.modiDate = modiDate;
       this.flag = flag;
       this.mp005 = mp005;
       this.mp006 = mp006;
       this.mp007 = mp007;
       this.mp008 = mp008;
       this.mp009 = mp009;
       this.mp010 = mp010;
       this.mp011 = mp011;
       this.mp012 = mp012;
       this.mp013 = mp013;
       this.mp014 = mp014;
       this.mp015 = mp015;
       this.udf01 = udf01;
       this.udf02 = udf02;
       this.udf03 = udf03;
       this.udf04 = udf04;
       this.udf05 = udf05;
       this.udf06 = udf06;
       this.udf51 = udf51;
       this.udf52 = udf52;
       this.udf53 = udf53;
       this.udf54 = udf54;
       this.udf55 = udf55;
       this.udf56 = udf56;
       this.udf07 = udf07;
       this.udf08 = udf08;
       this.udf09 = udf09;
       this.udf10 = udf10;
       this.udf11 = udf11;
       this.udf12 = udf12;
       this.udf57 = udf57;
       this.udf58 = udf58;
       this.udf59 = udf59;
       this.udf60 = udf60;
       this.udf61 = udf61;
       this.udf62 = udf62;
    }
   
    public BommpId getId() {
        return this.id;
    }
    
    public void setId(BommpId id) {
        this.id = id;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public String getUsrGroup() {
        return this.usrGroup;
    }
    
    public void setUsrGroup(String usrGroup) {
        this.usrGroup = usrGroup;
    }
    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public String getModiDate() {
        return this.modiDate;
    }
    
    public void setModiDate(String modiDate) {
        this.modiDate = modiDate;
    }
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }
    public BigDecimal getMp005() {
        return this.mp005;
    }
    
    public void setMp005(BigDecimal mp005) {
        this.mp005 = mp005;
    }
    public BigDecimal getMp006() {
        return this.mp006;
    }
    
    public void setMp006(BigDecimal mp006) {
        this.mp006 = mp006;
    }
    public String getMp007() {
        return this.mp007;
    }
    
    public void setMp007(String mp007) {
        this.mp007 = mp007;
    }
    public String getMp008() {
        return this.mp008;
    }
    
    public void setMp008(String mp008) {
        this.mp008 = mp008;
    }
    public String getMp009() {
        return this.mp009;
    }
    
    public void setMp009(String mp009) {
        this.mp009 = mp009;
    }
    public Character getMp010() {
        return this.mp010;
    }
    
    public void setMp010(Character mp010) {
        this.mp010 = mp010;
    }
    public String getMp011() {
        return this.mp011;
    }
    
    public void setMp011(String mp011) {
        this.mp011 = mp011;
    }
    public String getMp012() {
        return this.mp012;
    }
    
    public void setMp012(String mp012) {
        this.mp012 = mp012;
    }
    public BigDecimal getMp013() {
        return this.mp013;
    }
    
    public void setMp013(BigDecimal mp013) {
        this.mp013 = mp013;
    }
    public BigDecimal getMp014() {
        return this.mp014;
    }
    
    public void setMp014(BigDecimal mp014) {
        this.mp014 = mp014;
    }
    public BigDecimal getMp015() {
        return this.mp015;
    }
    
    public void setMp015(BigDecimal mp015) {
        this.mp015 = mp015;
    }
    public String getUdf01() {
        return this.udf01;
    }
    
    public void setUdf01(String udf01) {
        this.udf01 = udf01;
    }
    public String getUdf02() {
        return this.udf02;
    }
    
    public void setUdf02(String udf02) {
        this.udf02 = udf02;
    }
    public String getUdf03() {
        return this.udf03;
    }
    
    public void setUdf03(String udf03) {
        this.udf03 = udf03;
    }
    public String getUdf04() {
        return this.udf04;
    }
    
    public void setUdf04(String udf04) {
        this.udf04 = udf04;
    }
    public String getUdf05() {
        return this.udf05;
    }
    
    public void setUdf05(String udf05) {
        this.udf05 = udf05;
    }
    public String getUdf06() {
        return this.udf06;
    }
    
    public void setUdf06(String udf06) {
        this.udf06 = udf06;
    }
    public BigDecimal getUdf51() {
        return this.udf51;
    }
    
    public void setUdf51(BigDecimal udf51) {
        this.udf51 = udf51;
    }
    public BigDecimal getUdf52() {
        return this.udf52;
    }
    
    public void setUdf52(BigDecimal udf52) {
        this.udf52 = udf52;
    }
    public BigDecimal getUdf53() {
        return this.udf53;
    }
    
    public void setUdf53(BigDecimal udf53) {
        this.udf53 = udf53;
    }
    public BigDecimal getUdf54() {
        return this.udf54;
    }
    
    public void setUdf54(BigDecimal udf54) {
        this.udf54 = udf54;
    }
    public BigDecimal getUdf55() {
        return this.udf55;
    }
    
    public void setUdf55(BigDecimal udf55) {
        this.udf55 = udf55;
    }
    public BigDecimal getUdf56() {
        return this.udf56;
    }
    
    public void setUdf56(BigDecimal udf56) {
        this.udf56 = udf56;
    }
    public String getUdf07() {
        return this.udf07;
    }
    
    public void setUdf07(String udf07) {
        this.udf07 = udf07;
    }
    public String getUdf08() {
        return this.udf08;
    }
    
    public void setUdf08(String udf08) {
        this.udf08 = udf08;
    }
    public String getUdf09() {
        return this.udf09;
    }
    
    public void setUdf09(String udf09) {
        this.udf09 = udf09;
    }
    public String getUdf10() {
        return this.udf10;
    }
    
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }
    public String getUdf11() {
        return this.udf11;
    }
    
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }
    public String getUdf12() {
        return this.udf12;
    }
    
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }
    public BigDecimal getUdf57() {
        return this.udf57;
    }
    
    public void setUdf57(BigDecimal udf57) {
        this.udf57 = udf57;
    }
    public BigDecimal getUdf58() {
        return this.udf58;
    }
    
    public void setUdf58(BigDecimal udf58) {
        this.udf58 = udf58;
    }
    public BigDecimal getUdf59() {
        return this.udf59;
    }
    
    public void setUdf59(BigDecimal udf59) {
        this.udf59 = udf59;
    }
    public BigDecimal getUdf60() {
        return this.udf60;
    }
    
    public void setUdf60(BigDecimal udf60) {
        this.udf60 = udf60;
    }
    public BigDecimal getUdf61() {
        return this.udf61;
    }
    
    public void setUdf61(BigDecimal udf61) {
        this.udf61 = udf61;
    }
    public BigDecimal getUdf62() {
        return this.udf62;
    }
    
    public void setUdf62(BigDecimal udf62) {
        this.udf62 = udf62;
    }




}


