package com.edwin.bomtable;
// Generated Sep 9, 2013 11:12:54 PM by Hibernate Tools 3.6.0



/**
 * CoptqId generated by hbm2java
 */
public class CoptqId  implements java.io.Serializable {


     private String tq001;
     private String tq002;

    public CoptqId() {
    }

    public CoptqId(String tq001, String tq002) {
       this.tq001 = tq001;
       this.tq002 = tq002;
    }
   
    public String getTq001() {
        return this.tq001;
    }
    
    public void setTq001(String tq001) {
        this.tq001 = tq001;
    }
    public String getTq002() {
        return this.tq002;
    }
    
    public void setTq002(String tq002) {
        this.tq002 = tq002;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CoptqId) ) return false;
		 CoptqId castOther = ( CoptqId ) other; 
         
		 return ( (this.getTq001()==castOther.getTq001()) || ( this.getTq001()!=null && castOther.getTq001()!=null && this.getTq001().equals(castOther.getTq001()) ) )
 && ( (this.getTq002()==castOther.getTq002()) || ( this.getTq002()!=null && castOther.getTq002()!=null && this.getTq002().equals(castOther.getTq002()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTq001() == null ? 0 : this.getTq001().hashCode() );
         result = 37 * result + ( getTq002() == null ? 0 : this.getTq002().hashCode() );
         return result;
   }   


}


