package com.edwin.bomtable;
// Generated Sep 9, 2013 11:12:54 PM by Hibernate Tools 3.6.0



/**
 * CoptrId generated by hbm2java
 */
public class CoptrId  implements java.io.Serializable {


     private String tr001;
     private String tr002;
     private String tr003;

    public CoptrId() {
    }

    public CoptrId(String tr001, String tr002, String tr003) {
       this.tr001 = tr001;
       this.tr002 = tr002;
       this.tr003 = tr003;
    }
   
    public String getTr001() {
        return this.tr001;
    }
    
    public void setTr001(String tr001) {
        this.tr001 = tr001;
    }
    public String getTr002() {
        return this.tr002;
    }
    
    public void setTr002(String tr002) {
        this.tr002 = tr002;
    }
    public String getTr003() {
        return this.tr003;
    }
    
    public void setTr003(String tr003) {
        this.tr003 = tr003;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CoptrId) ) return false;
		 CoptrId castOther = ( CoptrId ) other; 
         
		 return ( (this.getTr001()==castOther.getTr001()) || ( this.getTr001()!=null && castOther.getTr001()!=null && this.getTr001().equals(castOther.getTr001()) ) )
 && ( (this.getTr002()==castOther.getTr002()) || ( this.getTr002()!=null && castOther.getTr002()!=null && this.getTr002().equals(castOther.getTr002()) ) )
 && ( (this.getTr003()==castOther.getTr003()) || ( this.getTr003()!=null && castOther.getTr003()!=null && this.getTr003().equals(castOther.getTr003()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTr001() == null ? 0 : this.getTr001().hashCode() );
         result = 37 * result + ( getTr002() == null ? 0 : this.getTr002().hashCode() );
         result = 37 * result + ( getTr003() == null ? 0 : this.getTr003().hashCode() );
         return result;
   }   


}


